// Generated by CIRCT firtool-1.149.0
module EccCodec(	// C:\\Users\\admin\\.bazel\\2ryzlsy4\\execroot\\_main\\hdl\\chisel\\src\\accel\\npu\\EccCodec.scala:85:7
  input         clock,	// C:\\Users\\admin\\.bazel\\2ryzlsy4\\execroot\\_main\\hdl\\chisel\\src\\accel\\npu\\EccCodec.scala:85:7
                reset,	// C:\\Users\\admin\\.bazel\\2ryzlsy4\\execroot\\_main\\hdl\\chisel\\src\\accel\\npu\\EccCodec.scala:85:7
  input  [7:0]  io_encodeData,	// C:\\Users\\admin\\.bazel\\2ryzlsy4\\execroot\\_main\\hdl\\chisel\\src\\accel\\npu\\EccCodec.scala:91:14
  output [12:0] io_encoded,	// C:\\Users\\admin\\.bazel\\2ryzlsy4\\execroot\\_main\\hdl\\chisel\\src\\accel\\npu\\EccCodec.scala:91:14
  input  [12:0] io_decodeData,	// C:\\Users\\admin\\.bazel\\2ryzlsy4\\execroot\\_main\\hdl\\chisel\\src\\accel\\npu\\EccCodec.scala:91:14
  output [7:0]  io_decoded,	// C:\\Users\\admin\\.bazel\\2ryzlsy4\\execroot\\_main\\hdl\\chisel\\src\\accel\\npu\\EccCodec.scala:91:14
  output [1:0]  io_errorStatus,	// C:\\Users\\admin\\.bazel\\2ryzlsy4\\execroot\\_main\\hdl\\chisel\\src\\accel\\npu\\EccCodec.scala:91:14
  output [3:0]  io_errorSyndrome	// C:\\Users\\admin\\.bazel\\2ryzlsy4\\execroot\\_main\\hdl\\chisel\\src\\accel\\npu\\EccCodec.scala:91:14
);

  wire       w_encodeParity_parity_0 =
    io_encodeData[0] ^ io_encodeData[1] ^ io_encodeData[3] ^ io_encodeData[4]
    ^ io_encodeData[6];	// C:\\Users\\admin\\.bazel\\2ryzlsy4\\execroot\\_main\\hdl\\chisel\\src\\accel\\npu\\EccCodec.scala:148:{31,37}
  wire       w_encodeParity_parity_1 =
    io_encodeData[0] ^ io_encodeData[2] ^ io_encodeData[3] ^ io_encodeData[5]
    ^ io_encodeData[6];	// C:\\Users\\admin\\.bazel\\2ryzlsy4\\execroot\\_main\\hdl\\chisel\\src\\accel\\npu\\EccCodec.scala:148:{31,37}
  wire       w_encodeParity_parity_2 =
    io_encodeData[1] ^ io_encodeData[2] ^ io_encodeData[3] ^ io_encodeData[7];	// C:\\Users\\admin\\.bazel\\2ryzlsy4\\execroot\\_main\\hdl\\chisel\\src\\accel\\npu\\EccCodec.scala:148:{31,37}
  wire       w_encodeParity_parity_3 =
    io_encodeData[4] ^ io_encodeData[5] ^ io_encodeData[6] ^ io_encodeData[7];	// C:\\Users\\admin\\.bazel\\2ryzlsy4\\execroot\\_main\\hdl\\chisel\\src\\accel\\npu\\EccCodec.scala:148:{31,37}
  wire       w_computedGlobalParity =
    io_decodeData[0] ^ io_decodeData[1] ^ io_decodeData[2] ^ io_decodeData[3]
    ^ io_decodeData[4] ^ io_decodeData[5] ^ io_decodeData[6] ^ io_decodeData[7]
    ^ io_decodeData[8] ^ io_decodeData[9] ^ io_decodeData[10] ^ io_decodeData[11];	// C:\\Users\\admin\\.bazel\\2ryzlsy4\\execroot\\_main\\hdl\\chisel\\src\\accel\\npu\\EccCodec.scala:148:37, :161:25, :164:{25,33}, :180:31, :181:33
  wire [3:0] w_syndrome =
    io_decodeData[11:8]
    ^ {io_decodeData[4] ^ io_decodeData[5] ^ io_decodeData[6] ^ io_decodeData[7],
       io_decodeData[1] ^ io_decodeData[2] ^ io_decodeData[3] ^ io_decodeData[7],
       io_decodeData[0] ^ io_decodeData[2] ^ io_decodeData[3] ^ io_decodeData[5]
         ^ io_decodeData[6],
       io_decodeData[0] ^ io_decodeData[1] ^ io_decodeData[3] ^ io_decodeData[4]
         ^ io_decodeData[6]};	// C:\\Users\\admin\\.bazel\\2ryzlsy4\\execroot\\_main\\hdl\\chisel\\src\\accel\\npu\\EccCodec.scala:148:{31,37}, :154:12, :180:31, :181:33, :196:31
  wire       w_singleError = (|w_syndrome) & io_decodeData[12] != w_computedGlobalParity;	// C:\\Users\\admin\\.bazel\\2ryzlsy4\\execroot\\_main\\hdl\\chisel\\src\\accel\\npu\\EccCodec.scala:161:25, :164:25, :182:39, :196:31, :199:46, :206:{35,44,47}
  assign io_encoded =
    {io_encodeData[0] ^ io_encodeData[1] ^ io_encodeData[2] ^ io_encodeData[3]
       ^ io_encodeData[4] ^ io_encodeData[5] ^ io_encodeData[6] ^ io_encodeData[7]
       ^ w_encodeParity_parity_0 ^ w_encodeParity_parity_1 ^ w_encodeParity_parity_2
       ^ w_encodeParity_parity_3,
     w_encodeParity_parity_3,
     w_encodeParity_parity_2,
     w_encodeParity_parity_1,
     w_encodeParity_parity_0,
     io_encodeData};	// C:\\Users\\admin\\.bazel\\2ryzlsy4\\execroot\\_main\\hdl\\chisel\\src\\accel\\npu\\EccCodec.scala:85:7, :148:{31,37}, :161:25, :164:25, :173:20
  assign io_decoded =
    {w_singleError & w_syndrome == 4'hC ^ io_decodeData[7],
     w_singleError & w_syndrome == 4'hB ^ io_decodeData[6],
     w_singleError & w_syndrome == 4'hA ^ io_decodeData[5],
     w_singleError & w_syndrome == 4'h9 ^ io_decodeData[4],
     w_singleError & w_syndrome == 4'h7 ^ io_decodeData[3],
     w_singleError & w_syndrome == 4'h6 ^ io_decodeData[2],
     w_singleError & w_syndrome == 4'h5 ^ io_decodeData[1],
     w_singleError & w_syndrome == 4'h3 ^ io_decodeData[0]};	// C:\\Users\\admin\\.bazel\\2ryzlsy4\\execroot\\_main\\hdl\\chisel\\src\\accel\\npu\\EccCodec.scala:85:7, :148:37, :180:31, :196:31, :206:44, :226:23, :229:23, :233:{23,34}, :234:29, :240:32
  assign io_errorStatus =
    w_syndrome == 4'h0 & io_decodeData[12] == w_computedGlobalParity
      ? 2'h0
      : w_singleError ? 2'h1 : 2'h2;	// C:\\Users\\admin\\.bazel\\2ryzlsy4\\execroot\\_main\\hdl\\chisel\\src\\accel\\npu\\EccCodec.scala:85:7, :161:25, :164:25, :182:39, :196:31, :199:46, :205:{31,40}, :206:44, :212:24, :213:8
  assign io_errorSyndrome = w_syndrome;	// C:\\Users\\admin\\.bazel\\2ryzlsy4\\execroot\\_main\\hdl\\chisel\\src\\accel\\npu\\EccCodec.scala:85:7, :196:31
endmodule

