// Generated by CIRCT firtool-1.149.0

// Include register initializers in init blocks unless synthesis is set
`ifndef RANDOMIZE
  `ifdef RANDOMIZE_REG_INIT
    `define RANDOMIZE
  `endif // RANDOMIZE_REG_INIT
`endif // not def RANDOMIZE
`ifndef SYNTHESIS
  `ifndef ENABLE_INITIAL_REG_
    `define ENABLE_INITIAL_REG_
  `endif // not def ENABLE_INITIAL_REG_
`endif // not def SYNTHESIS


// Include rmemory initializers in init blocks unless synthesis is set
`ifndef RANDOMIZE
  `ifdef RANDOMIZE_MEM_INIT
    `define RANDOMIZE
  `endif // RANDOMIZE_MEM_INIT
`endif // not def RANDOMIZE
`ifndef SYNTHESIS
  `ifndef ENABLE_INITIAL_MEM_
    `define ENABLE_INITIAL_MEM_
  `endif // not def ENABLE_INITIAL_MEM_
`endif // not def SYNTHESIS

// Standard header to adapt well known macros for register randomization.

// RANDOM may be set to an expression that produces a 32-bit random unsigned value.
`ifndef RANDOM
  `define RANDOM $random
`endif // not def RANDOM

// Users can define INIT_RANDOM as general code that gets injected into the
// initializer block for modules with registers.
`ifndef INIT_RANDOM
  `define INIT_RANDOM
`endif // not def INIT_RANDOM

// If using random initialization, you can also define RANDOMIZE_DELAY to
// customize the delay used, otherwise 0.002 is used.
`ifndef RANDOMIZE_DELAY
  `define RANDOMIZE_DELAY 0.002
`endif // not def RANDOMIZE_DELAY

// Define INIT_RANDOM_PROLOG_ for use in our modules below.
`ifndef INIT_RANDOM_PROLOG_
  `ifdef RANDOMIZE
    `ifdef VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM
    `else  // VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM #`RANDOMIZE_DELAY begin end
    `endif // VERILATOR
  `else  // RANDOMIZE
    `define INIT_RANDOM_PROLOG_
  `endif // RANDOMIZE
`endif // not def INIT_RANDOM_PROLOG_
// VCS coverage exclude_file
module mem_256x64(	// C:\\Users\\admin\\.bazel\\2ryzlsy4\\execroot\\_main\\hdl\\chisel\\src\\accel\\npu\\NpuSram.scala:116:24
  input  [7:0]  R0_addr,
  input         R0_en,
                R0_clk,
  output [63:0] R0_data,
  input  [7:0]  R1_addr,
  input         R1_en,
                R1_clk,
  output [63:0] R1_data,
  input  [7:0]  W0_addr,
  input         W0_en,
                W0_clk,
  input  [63:0] W0_data,
  input  [7:0]  W1_addr,
  input         W1_en,
                W1_clk,
  input  [63:0] W1_data,
  input  [7:0]  W2_addr,
  input         W2_en,
                W2_clk,
  input  [63:0] W2_data,
  input  [7:0]  W3_addr,
  input         W3_en,
                W3_clk,
  input  [63:0] W3_data
);

  reg [63:0] Memory[0:255];	// C:\\Users\\admin\\.bazel\\2ryzlsy4\\execroot\\_main\\hdl\\chisel\\src\\accel\\npu\\NpuSram.scala:116:24
  reg        _R0_en_d0;	// C:\\Users\\admin\\.bazel\\2ryzlsy4\\execroot\\_main\\hdl\\chisel\\src\\accel\\npu\\NpuSram.scala:116:24
  reg [7:0]  _R0_addr_d0;	// C:\\Users\\admin\\.bazel\\2ryzlsy4\\execroot\\_main\\hdl\\chisel\\src\\accel\\npu\\NpuSram.scala:116:24
  always @(posedge R0_clk) begin	// C:\\Users\\admin\\.bazel\\2ryzlsy4\\execroot\\_main\\hdl\\chisel\\src\\accel\\npu\\NpuSram.scala:116:24
    _R0_en_d0 <= R0_en;	// C:\\Users\\admin\\.bazel\\2ryzlsy4\\execroot\\_main\\hdl\\chisel\\src\\accel\\npu\\NpuSram.scala:116:24
    _R0_addr_d0 <= R0_addr;	// C:\\Users\\admin\\.bazel\\2ryzlsy4\\execroot\\_main\\hdl\\chisel\\src\\accel\\npu\\NpuSram.scala:116:24
  end // always @(posedge)
  reg        _R1_en_d0;	// C:\\Users\\admin\\.bazel\\2ryzlsy4\\execroot\\_main\\hdl\\chisel\\src\\accel\\npu\\NpuSram.scala:116:24
  reg [7:0]  _R1_addr_d0;	// C:\\Users\\admin\\.bazel\\2ryzlsy4\\execroot\\_main\\hdl\\chisel\\src\\accel\\npu\\NpuSram.scala:116:24
  always @(posedge R1_clk) begin	// C:\\Users\\admin\\.bazel\\2ryzlsy4\\execroot\\_main\\hdl\\chisel\\src\\accel\\npu\\NpuSram.scala:116:24
    _R1_en_d0 <= R1_en;	// C:\\Users\\admin\\.bazel\\2ryzlsy4\\execroot\\_main\\hdl\\chisel\\src\\accel\\npu\\NpuSram.scala:116:24
    _R1_addr_d0 <= R1_addr;	// C:\\Users\\admin\\.bazel\\2ryzlsy4\\execroot\\_main\\hdl\\chisel\\src\\accel\\npu\\NpuSram.scala:116:24
  end // always @(posedge)
  always @(posedge W0_clk) begin	// C:\\Users\\admin\\.bazel\\2ryzlsy4\\execroot\\_main\\hdl\\chisel\\src\\accel\\npu\\NpuSram.scala:116:24
    if (W0_en)	// C:\\Users\\admin\\.bazel\\2ryzlsy4\\execroot\\_main\\hdl\\chisel\\src\\accel\\npu\\NpuSram.scala:116:24
      Memory[W0_addr] <= W0_data;	// C:\\Users\\admin\\.bazel\\2ryzlsy4\\execroot\\_main\\hdl\\chisel\\src\\accel\\npu\\NpuSram.scala:116:24
    if (W1_en)	// C:\\Users\\admin\\.bazel\\2ryzlsy4\\execroot\\_main\\hdl\\chisel\\src\\accel\\npu\\NpuSram.scala:116:24
      Memory[W1_addr] <= W1_data;	// C:\\Users\\admin\\.bazel\\2ryzlsy4\\execroot\\_main\\hdl\\chisel\\src\\accel\\npu\\NpuSram.scala:116:24
    if (W2_en)	// C:\\Users\\admin\\.bazel\\2ryzlsy4\\execroot\\_main\\hdl\\chisel\\src\\accel\\npu\\NpuSram.scala:116:24
      Memory[W2_addr] <= W2_data;	// C:\\Users\\admin\\.bazel\\2ryzlsy4\\execroot\\_main\\hdl\\chisel\\src\\accel\\npu\\NpuSram.scala:116:24
    if (W3_en)	// C:\\Users\\admin\\.bazel\\2ryzlsy4\\execroot\\_main\\hdl\\chisel\\src\\accel\\npu\\NpuSram.scala:116:24
      Memory[W3_addr] <= W3_data;	// C:\\Users\\admin\\.bazel\\2ryzlsy4\\execroot\\_main\\hdl\\chisel\\src\\accel\\npu\\NpuSram.scala:116:24
  end // always @(posedge)
  `ifdef ENABLE_INITIAL_MEM_	// C:\\Users\\admin\\.bazel\\2ryzlsy4\\execroot\\_main\\hdl\\chisel\\src\\accel\\npu\\NpuSram.scala:116:24
    `ifdef RANDOMIZE_REG_INIT	// C:\\Users\\admin\\.bazel\\2ryzlsy4\\execroot\\_main\\hdl\\chisel\\src\\accel\\npu\\NpuSram.scala:116:24
      reg [31:0] _RANDOM;	// C:\\Users\\admin\\.bazel\\2ryzlsy4\\execroot\\_main\\hdl\\chisel\\src\\accel\\npu\\NpuSram.scala:116:24
    `endif // RANDOMIZE_REG_INIT
    reg [63:0] _RANDOM_MEM;	// C:\\Users\\admin\\.bazel\\2ryzlsy4\\execroot\\_main\\hdl\\chisel\\src\\accel\\npu\\NpuSram.scala:116:24
    initial begin	// C:\\Users\\admin\\.bazel\\2ryzlsy4\\execroot\\_main\\hdl\\chisel\\src\\accel\\npu\\NpuSram.scala:116:24
      `INIT_RANDOM_PROLOG_	// C:\\Users\\admin\\.bazel\\2ryzlsy4\\execroot\\_main\\hdl\\chisel\\src\\accel\\npu\\NpuSram.scala:116:24
      `ifdef RANDOMIZE_MEM_INIT	// C:\\Users\\admin\\.bazel\\2ryzlsy4\\execroot\\_main\\hdl\\chisel\\src\\accel\\npu\\NpuSram.scala:116:24
        for (logic [8:0] i = 9'h0; i < 9'h100; i += 9'h1) begin
          for (logic [6:0] j = 7'h0; j < 7'h40; j += 7'h20) begin
            _RANDOM_MEM[j[5:0] +: 32] = `RANDOM;	// C:\\Users\\admin\\.bazel\\2ryzlsy4\\execroot\\_main\\hdl\\chisel\\src\\accel\\npu\\NpuSram.scala:116:24
          end
          Memory[i[7:0]] = _RANDOM_MEM;	// C:\\Users\\admin\\.bazel\\2ryzlsy4\\execroot\\_main\\hdl\\chisel\\src\\accel\\npu\\NpuSram.scala:116:24
        end
      `endif // RANDOMIZE_MEM_INIT
      `ifdef RANDOMIZE_REG_INIT	// C:\\Users\\admin\\.bazel\\2ryzlsy4\\execroot\\_main\\hdl\\chisel\\src\\accel\\npu\\NpuSram.scala:116:24
        _RANDOM = {`RANDOM};	// C:\\Users\\admin\\.bazel\\2ryzlsy4\\execroot\\_main\\hdl\\chisel\\src\\accel\\npu\\NpuSram.scala:116:24
        _R0_en_d0 = _RANDOM[0];	// C:\\Users\\admin\\.bazel\\2ryzlsy4\\execroot\\_main\\hdl\\chisel\\src\\accel\\npu\\NpuSram.scala:116:24
        _R0_addr_d0 = _RANDOM[8:1];	// C:\\Users\\admin\\.bazel\\2ryzlsy4\\execroot\\_main\\hdl\\chisel\\src\\accel\\npu\\NpuSram.scala:116:24
        _R1_en_d0 = _RANDOM[9];	// C:\\Users\\admin\\.bazel\\2ryzlsy4\\execroot\\_main\\hdl\\chisel\\src\\accel\\npu\\NpuSram.scala:116:24
        _R1_addr_d0 = _RANDOM[17:10];	// C:\\Users\\admin\\.bazel\\2ryzlsy4\\execroot\\_main\\hdl\\chisel\\src\\accel\\npu\\NpuSram.scala:116:24
      `endif // RANDOMIZE_REG_INIT
    end // initial
  `endif // ENABLE_INITIAL_MEM_
  assign R0_data = _R0_en_d0 ? Memory[_R0_addr_d0] : 64'bx;	// C:\\Users\\admin\\.bazel\\2ryzlsy4\\execroot\\_main\\hdl\\chisel\\src\\accel\\npu\\NpuSram.scala:116:24
  assign R1_data = _R1_en_d0 ? Memory[_R1_addr_d0] : 64'bx;	// C:\\Users\\admin\\.bazel\\2ryzlsy4\\execroot\\_main\\hdl\\chisel\\src\\accel\\npu\\NpuSram.scala:116:24
endmodule

module NpuSram(	// C:\\Users\\admin\\.bazel\\2ryzlsy4\\execroot\\_main\\hdl\\chisel\\src\\accel\\npu\\NpuSram.scala:68:7
  input         clock,	// C:\\Users\\admin\\.bazel\\2ryzlsy4\\execroot\\_main\\hdl\\chisel\\src\\accel\\npu\\NpuSram.scala:68:7
                reset,	// C:\\Users\\admin\\.bazel\\2ryzlsy4\\execroot\\_main\\hdl\\chisel\\src\\accel\\npu\\NpuSram.scala:68:7
                io_portA_ren,	// C:\\Users\\admin\\.bazel\\2ryzlsy4\\execroot\\_main\\hdl\\chisel\\src\\accel\\npu\\NpuSram.scala:74:14
                io_portA_wen,	// C:\\Users\\admin\\.bazel\\2ryzlsy4\\execroot\\_main\\hdl\\chisel\\src\\accel\\npu\\NpuSram.scala:74:14
  input  [7:0]  io_portA_addr,	// C:\\Users\\admin\\.bazel\\2ryzlsy4\\execroot\\_main\\hdl\\chisel\\src\\accel\\npu\\NpuSram.scala:74:14
  input  [63:0] io_portA_wdata,	// C:\\Users\\admin\\.bazel\\2ryzlsy4\\execroot\\_main\\hdl\\chisel\\src\\accel\\npu\\NpuSram.scala:74:14
  input  [7:0]  io_portA_wstrb,	// C:\\Users\\admin\\.bazel\\2ryzlsy4\\execroot\\_main\\hdl\\chisel\\src\\accel\\npu\\NpuSram.scala:74:14
  output [63:0] io_portA_rdata,	// C:\\Users\\admin\\.bazel\\2ryzlsy4\\execroot\\_main\\hdl\\chisel\\src\\accel\\npu\\NpuSram.scala:74:14
  input         io_portB_ren,	// C:\\Users\\admin\\.bazel\\2ryzlsy4\\execroot\\_main\\hdl\\chisel\\src\\accel\\npu\\NpuSram.scala:74:14
                io_portB_wen,	// C:\\Users\\admin\\.bazel\\2ryzlsy4\\execroot\\_main\\hdl\\chisel\\src\\accel\\npu\\NpuSram.scala:74:14
  input  [7:0]  io_portB_addr,	// C:\\Users\\admin\\.bazel\\2ryzlsy4\\execroot\\_main\\hdl\\chisel\\src\\accel\\npu\\NpuSram.scala:74:14
  input  [63:0] io_portB_wdata,	// C:\\Users\\admin\\.bazel\\2ryzlsy4\\execroot\\_main\\hdl\\chisel\\src\\accel\\npu\\NpuSram.scala:74:14
  input  [7:0]  io_portB_wstrb,	// C:\\Users\\admin\\.bazel\\2ryzlsy4\\execroot\\_main\\hdl\\chisel\\src\\accel\\npu\\NpuSram.scala:74:14
  output [63:0] io_portB_rdata,	// C:\\Users\\admin\\.bazel\\2ryzlsy4\\execroot\\_main\\hdl\\chisel\\src\\accel\\npu\\NpuSram.scala:74:14
  input         io_bistMode,	// C:\\Users\\admin\\.bazel\\2ryzlsy4\\execroot\\_main\\hdl\\chisel\\src\\accel\\npu\\NpuSram.scala:74:14
                io_bistRen,	// C:\\Users\\admin\\.bazel\\2ryzlsy4\\execroot\\_main\\hdl\\chisel\\src\\accel\\npu\\NpuSram.scala:74:14
                io_bistWen,	// C:\\Users\\admin\\.bazel\\2ryzlsy4\\execroot\\_main\\hdl\\chisel\\src\\accel\\npu\\NpuSram.scala:74:14
  input  [7:0]  io_bistAddr,	// C:\\Users\\admin\\.bazel\\2ryzlsy4\\execroot\\_main\\hdl\\chisel\\src\\accel\\npu\\NpuSram.scala:74:14
  input  [63:0] io_bistWdata,	// C:\\Users\\admin\\.bazel\\2ryzlsy4\\execroot\\_main\\hdl\\chisel\\src\\accel\\npu\\NpuSram.scala:74:14
  input  [7:0]  io_bistWstrb,	// C:\\Users\\admin\\.bazel\\2ryzlsy4\\execroot\\_main\\hdl\\chisel\\src\\accel\\npu\\NpuSram.scala:74:14
  output [63:0] io_bistRdata,	// C:\\Users\\admin\\.bazel\\2ryzlsy4\\execroot\\_main\\hdl\\chisel\\src\\accel\\npu\\NpuSram.scala:74:14
  input         io_testEnable,	// C:\\Users\\admin\\.bazel\\2ryzlsy4\\execroot\\_main\\hdl\\chisel\\src\\accel\\npu\\NpuSram.scala:74:14
  output        io_clockGateEnable	// C:\\Users\\admin\\.bazel\\2ryzlsy4\\execroot\\_main\\hdl\\chisel\\src\\accel\\npu\\NpuSram.scala:74:14
);

  wire [63:0] _mem_ext_R0_data;	// C:\\Users\\admin\\.bazel\\2ryzlsy4\\execroot\\_main\\hdl\\chisel\\src\\accel\\npu\\NpuSram.scala:116:24
  wire [63:0] _mem_ext_R1_data;	// C:\\Users\\admin\\.bazel\\2ryzlsy4\\execroot\\_main\\hdl\\chisel\\src\\accel\\npu\\NpuSram.scala:116:24
  wire        effA_ren = io_bistMode ? io_bistRen : io_portA_ren;	// C:\\Users\\admin\\.bazel\\2ryzlsy4\\execroot\\_main\\hdl\\chisel\\src\\accel\\npu\\NpuSram.scala:130:23
  wire        effA_wen = io_bistMode ? io_bistWen : io_portA_wen;	// C:\\Users\\admin\\.bazel\\2ryzlsy4\\execroot\\_main\\hdl\\chisel\\src\\accel\\npu\\NpuSram.scala:131:23
  wire [7:0]  effA_addr = io_bistMode ? io_bistAddr : io_portA_addr;	// C:\\Users\\admin\\.bazel\\2ryzlsy4\\execroot\\_main\\hdl\\chisel\\src\\accel\\npu\\NpuSram.scala:132:23
  wire [63:0] effA_wdata = io_bistMode ? io_bistWdata : io_portA_wdata;	// C:\\Users\\admin\\.bazel\\2ryzlsy4\\execroot\\_main\\hdl\\chisel\\src\\accel\\npu\\NpuSram.scala:133:23
  wire [7:0]  effA_wstrb = io_bistMode ? io_bistWstrb : io_portA_wstrb;	// C:\\Users\\admin\\.bazel\\2ryzlsy4\\execroot\\_main\\hdl\\chisel\\src\\accel\\npu\\NpuSram.scala:134:23
  wire        effB_ren = ~io_bistMode & io_portB_ren;	// C:\\Users\\admin\\.bazel\\2ryzlsy4\\execroot\\_main\\hdl\\chisel\\src\\accel\\npu\\NpuSram.scala:138:23
  wire        effB_wen = ~io_bistMode & io_portB_wen;	// C:\\Users\\admin\\.bazel\\2ryzlsy4\\execroot\\_main\\hdl\\chisel\\src\\accel\\npu\\NpuSram.scala:138:23, :139:23
  mem_256x64 mem_ext (	// C:\\Users\\admin\\.bazel\\2ryzlsy4\\execroot\\_main\\hdl\\chisel\\src\\accel\\npu\\NpuSram.scala:116:24
    .R0_addr (io_portB_addr),
    .R0_en   (effB_ren & ~effB_wen | effB_wen & ~(&io_portB_wstrb)),	// C:\\Users\\admin\\.bazel\\2ryzlsy4\\execroot\\_main\\hdl\\chisel\\src\\accel\\npu\\NpuSram.scala:138:23, :139:23, :209:{14,17,29}, :213:{28,31,42}
    .R0_clk  (clock),
    .R0_data (_mem_ext_R0_data),
    .R1_addr (effA_addr),	// C:\\Users\\admin\\.bazel\\2ryzlsy4\\execroot\\_main\\hdl\\chisel\\src\\accel\\npu\\NpuSram.scala:132:23
    .R1_en   (effA_ren & ~effA_wen | effA_wen & ~(&effA_wstrb)),	// C:\\Users\\admin\\.bazel\\2ryzlsy4\\execroot\\_main\\hdl\\chisel\\src\\accel\\npu\\NpuSram.scala:130:23, :131:23, :134:23, :153:{14,17,29}, :157:{28,31,42}
    .R1_clk  (clock),
    .R1_data (_mem_ext_R1_data),
    .W0_addr (io_portB_addr),
    .W0_en   (effB_wen & ~(&io_portB_wstrb)),	// C:\\Users\\admin\\.bazel\\2ryzlsy4\\execroot\\_main\\hdl\\chisel\\src\\accel\\npu\\NpuSram.scala:116:24, :139:23, :209:29, :235:18, :240:29, :249:18
    .W0_clk  (clock),
    .W0_data
      ({io_portB_wstrb[7] ? io_portB_wdata[63:56] : _mem_ext_R0_data[63:56],
        io_portB_wstrb[6] ? io_portB_wdata[55:48] : _mem_ext_R0_data[55:48],
        io_portB_wstrb[5] ? io_portB_wdata[47:40] : _mem_ext_R0_data[47:40],
        io_portB_wstrb[4] ? io_portB_wdata[39:32] : _mem_ext_R0_data[39:32],
        io_portB_wstrb[3] ? io_portB_wdata[31:24] : _mem_ext_R0_data[31:24],
        io_portB_wstrb[2] ? io_portB_wdata[23:16] : _mem_ext_R0_data[23:16],
        io_portB_wstrb[1] ? io_portB_wdata[15:8] : _mem_ext_R0_data[15:8],
        io_portB_wstrb[0] ? io_portB_wdata[7:0] : _mem_ext_R0_data[7:0]}),	// C:\\Users\\admin\\.bazel\\2ryzlsy4\\execroot\\_main\\hdl\\chisel\\src\\accel\\npu\\NpuSram.scala:116:24, :247:{30,41,56,75}, :249:40
    .W1_addr (io_portB_addr),
    .W1_en   (effB_wen & (&io_portB_wstrb)),	// C:\\Users\\admin\\.bazel\\2ryzlsy4\\execroot\\_main\\hdl\\chisel\\src\\accel\\npu\\NpuSram.scala:116:24, :139:23, :209:29, :235:18, :240:29
    .W1_clk  (clock),
    .W1_data (io_portB_wdata),
    .W2_addr (effA_addr),	// C:\\Users\\admin\\.bazel\\2ryzlsy4\\execroot\\_main\\hdl\\chisel\\src\\accel\\npu\\NpuSram.scala:132:23
    .W2_en   (effA_wen & ~(&effA_wstrb)),	// C:\\Users\\admin\\.bazel\\2ryzlsy4\\execroot\\_main\\hdl\\chisel\\src\\accel\\npu\\NpuSram.scala:116:24, :131:23, :134:23, :153:29, :182:18, :188:29, :199:18
    .W2_clk  (clock),
    .W2_data
      ({effA_wstrb[7] ? effA_wdata[63:56] : _mem_ext_R1_data[63:56],
        effA_wstrb[6] ? effA_wdata[55:48] : _mem_ext_R1_data[55:48],
        effA_wstrb[5] ? effA_wdata[47:40] : _mem_ext_R1_data[47:40],
        effA_wstrb[4] ? effA_wdata[39:32] : _mem_ext_R1_data[39:32],
        effA_wstrb[3] ? effA_wdata[31:24] : _mem_ext_R1_data[31:24],
        effA_wstrb[2] ? effA_wdata[23:16] : _mem_ext_R1_data[23:16],
        effA_wstrb[1] ? effA_wdata[15:8] : _mem_ext_R1_data[15:8],
        effA_wstrb[0] ? effA_wdata[7:0] : _mem_ext_R1_data[7:0]}),	// C:\\Users\\admin\\.bazel\\2ryzlsy4\\execroot\\_main\\hdl\\chisel\\src\\accel\\npu\\NpuSram.scala:116:24, :133:23, :134:23, :197:{30,41,56,75}, :199:40
    .W3_addr (effA_addr),	// C:\\Users\\admin\\.bazel\\2ryzlsy4\\execroot\\_main\\hdl\\chisel\\src\\accel\\npu\\NpuSram.scala:132:23
    .W3_en   (effA_wen & (&effA_wstrb)),	// C:\\Users\\admin\\.bazel\\2ryzlsy4\\execroot\\_main\\hdl\\chisel\\src\\accel\\npu\\NpuSram.scala:116:24, :131:23, :134:23, :153:29, :182:18, :188:29
    .W3_clk  (clock),
    .W3_data (effA_wdata)	// C:\\Users\\admin\\.bazel\\2ryzlsy4\\execroot\\_main\\hdl\\chisel\\src\\accel\\npu\\NpuSram.scala:133:23
  );	// C:\\Users\\admin\\.bazel\\2ryzlsy4\\execroot\\_main\\hdl\\chisel\\src\\accel\\npu\\NpuSram.scala:116:24
  assign io_portA_rdata = _mem_ext_R1_data;	// C:\\Users\\admin\\.bazel\\2ryzlsy4\\execroot\\_main\\hdl\\chisel\\src\\accel\\npu\\NpuSram.scala:68:7, :116:24
  assign io_portB_rdata = _mem_ext_R0_data;	// C:\\Users\\admin\\.bazel\\2ryzlsy4\\execroot\\_main\\hdl\\chisel\\src\\accel\\npu\\NpuSram.scala:68:7, :116:24
  assign io_bistRdata = _mem_ext_R1_data;	// C:\\Users\\admin\\.bazel\\2ryzlsy4\\execroot\\_main\\hdl\\chisel\\src\\accel\\npu\\NpuSram.scala:68:7, :116:24
  assign io_clockGateEnable =
    effA_ren | effA_wen | effB_ren | effB_wen | io_bistMode | io_testEnable;	// C:\\Users\\admin\\.bazel\\2ryzlsy4\\execroot\\_main\\hdl\\chisel\\src\\accel\\npu\\NpuSram.scala:68:7, :130:23, :131:23, :138:23, :139:23, :266:{34,46,58,70,85}
endmodule

