// Generated by CIRCT firtool-1.149.0

// Include register initializers in init blocks unless synthesis is set
`ifndef RANDOMIZE
  `ifdef RANDOMIZE_REG_INIT
    `define RANDOMIZE
  `endif // RANDOMIZE_REG_INIT
`endif // not def RANDOMIZE
`ifndef SYNTHESIS
  `ifndef ENABLE_INITIAL_REG_
    `define ENABLE_INITIAL_REG_
  `endif // not def ENABLE_INITIAL_REG_
`endif // not def SYNTHESIS

// Standard header to adapt well known macros for register randomization.

// RANDOM may be set to an expression that produces a 32-bit random unsigned value.
`ifndef RANDOM
  `define RANDOM $random
`endif // not def RANDOM

// Users can define INIT_RANDOM as general code that gets injected into the
// initializer block for modules with registers.
`ifndef INIT_RANDOM
  `define INIT_RANDOM
`endif // not def INIT_RANDOM

// If using random initialization, you can also define RANDOMIZE_DELAY to
// customize the delay used, otherwise 0.002 is used.
`ifndef RANDOMIZE_DELAY
  `define RANDOMIZE_DELAY 0.002
`endif // not def RANDOMIZE_DELAY

// Define INIT_RANDOM_PROLOG_ for use in our modules below.
`ifndef INIT_RANDOM_PROLOG_
  `ifdef RANDOMIZE
    `ifdef VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM
    `else  // VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM #`RANDOMIZE_DELAY begin end
    `endif // VERILATOR
  `else  // RANDOMIZE
    `define INIT_RANDOM_PROLOG_
  `endif // RANDOMIZE
`endif // not def INIT_RANDOM_PROLOG_
module NpuCore(	// C:\\Users\\admin\\.bazel\\2ryzlsy4\\execroot\\_main\\hdl\\chisel\\src\\accel\\npu\\NpuCore.scala:190:7
  input         clock,	// C:\\Users\\admin\\.bazel\\2ryzlsy4\\execroot\\_main\\hdl\\chisel\\src\\accel\\npu\\NpuCore.scala:190:7
                reset,	// C:\\Users\\admin\\.bazel\\2ryzlsy4\\execroot\\_main\\hdl\\chisel\\src\\accel\\npu\\NpuCore.scala:190:7
  output        io_cmd_ready,	// C:\\Users\\admin\\.bazel\\2ryzlsy4\\execroot\\_main\\hdl\\chisel\\src\\accel\\npu\\NpuCore.scala:191:14
  input         io_cmd_valid,	// C:\\Users\\admin\\.bazel\\2ryzlsy4\\execroot\\_main\\hdl\\chisel\\src\\accel\\npu\\NpuCore.scala:191:14
  input  [2:0]  io_cmd_bits_opcode,	// C:\\Users\\admin\\.bazel\\2ryzlsy4\\execroot\\_main\\hdl\\chisel\\src\\accel\\npu\\NpuCore.scala:191:14
  input  [63:0] io_cmd_bits_srcAddr,	// C:\\Users\\admin\\.bazel\\2ryzlsy4\\execroot\\_main\\hdl\\chisel\\src\\accel\\npu\\NpuCore.scala:191:14
                io_cmd_bits_dstAddr,	// C:\\Users\\admin\\.bazel\\2ryzlsy4\\execroot\\_main\\hdl\\chisel\\src\\accel\\npu\\NpuCore.scala:191:14
  input  [15:0] io_cmd_bits_dimM,	// C:\\Users\\admin\\.bazel\\2ryzlsy4\\execroot\\_main\\hdl\\chisel\\src\\accel\\npu\\NpuCore.scala:191:14
                io_cmd_bits_dimN,	// C:\\Users\\admin\\.bazel\\2ryzlsy4\\execroot\\_main\\hdl\\chisel\\src\\accel\\npu\\NpuCore.scala:191:14
                io_cmd_bits_dimK,	// C:\\Users\\admin\\.bazel\\2ryzlsy4\\execroot\\_main\\hdl\\chisel\\src\\accel\\npu\\NpuCore.scala:191:14
  output        io_status_done,	// C:\\Users\\admin\\.bazel\\2ryzlsy4\\execroot\\_main\\hdl\\chisel\\src\\accel\\npu\\NpuCore.scala:191:14
                io_status_error,	// C:\\Users\\admin\\.bazel\\2ryzlsy4\\execroot\\_main\\hdl\\chisel\\src\\accel\\npu\\NpuCore.scala:191:14
  input         io_dmaReq_ready,	// C:\\Users\\admin\\.bazel\\2ryzlsy4\\execroot\\_main\\hdl\\chisel\\src\\accel\\npu\\NpuCore.scala:191:14
  output        io_dmaReq_valid,	// C:\\Users\\admin\\.bazel\\2ryzlsy4\\execroot\\_main\\hdl\\chisel\\src\\accel\\npu\\NpuCore.scala:191:14
  output [63:0] io_dmaReq_bits_addr,	// C:\\Users\\admin\\.bazel\\2ryzlsy4\\execroot\\_main\\hdl\\chisel\\src\\accel\\npu\\NpuCore.scala:191:14
  output [15:0] io_dmaReq_bits_len,	// C:\\Users\\admin\\.bazel\\2ryzlsy4\\execroot\\_main\\hdl\\chisel\\src\\accel\\npu\\NpuCore.scala:191:14
  output        io_dmaReq_bits_isLoad,	// C:\\Users\\admin\\.bazel\\2ryzlsy4\\execroot\\_main\\hdl\\chisel\\src\\accel\\npu\\NpuCore.scala:191:14
  input         io_dmaResp_valid	// C:\\Users\\admin\\.bazel\\2ryzlsy4\\execroot\\_main\\hdl\\chisel\\src\\accel\\npu\\NpuCore.scala:191:14
);

  reg  [2:0]  rState;	// C:\\Users\\admin\\.bazel\\2ryzlsy4\\execroot\\_main\\hdl\\chisel\\src\\accel\\npu\\NpuCore.scala:261:25
  reg  [63:0] rCmd_srcAddr;	// C:\\Users\\admin\\.bazel\\2ryzlsy4\\execroot\\_main\\hdl\\chisel\\src\\accel\\npu\\NpuCore.scala:262:21
  reg  [63:0] rCmd_dstAddr;	// C:\\Users\\admin\\.bazel\\2ryzlsy4\\execroot\\_main\\hdl\\chisel\\src\\accel\\npu\\NpuCore.scala:262:21
  reg  [15:0] rDimM;	// C:\\Users\\admin\\.bazel\\2ryzlsy4\\execroot\\_main\\hdl\\chisel\\src\\accel\\npu\\NpuCore.scala:263:25
  reg  [15:0] rDimN;	// C:\\Users\\admin\\.bazel\\2ryzlsy4\\execroot\\_main\\hdl\\chisel\\src\\accel\\npu\\NpuCore.scala:264:25
  reg  [15:0] rDimK;	// C:\\Users\\admin\\.bazel\\2ryzlsy4\\execroot\\_main\\hdl\\chisel\\src\\accel\\npu\\NpuCore.scala:265:25
  reg  [15:0] rRowIdx;	// C:\\Users\\admin\\.bazel\\2ryzlsy4\\execroot\\_main\\hdl\\chisel\\src\\accel\\npu\\NpuCore.scala:266:25
  reg  [15:0] rColIdx;	// C:\\Users\\admin\\.bazel\\2ryzlsy4\\execroot\\_main\\hdl\\chisel\\src\\accel\\npu\\NpuCore.scala:267:25
  reg  [1:0]  rPhase;	// C:\\Users\\admin\\.bazel\\2ryzlsy4\\execroot\\_main\\hdl\\chisel\\src\\accel\\npu\\NpuCore.scala:268:25
  reg         rDmaActive;	// C:\\Users\\admin\\.bazel\\2ryzlsy4\\execroot\\_main\\hdl\\chisel\\src\\accel\\npu\\NpuCore.scala:275:27
  wire        _GEN = rState == 3'h1;	// C:\\Users\\admin\\.bazel\\2ryzlsy4\\execroot\\_main\\hdl\\chisel\\src\\accel\\npu\\NpuCore.scala:261:25, :331:18, :461:24
  wire        _GEN_0 = rState == 3'h2;	// C:\\Users\\admin\\.bazel\\2ryzlsy4\\execroot\\_main\\hdl\\chisel\\src\\accel\\npu\\NpuCore.scala:261:25, :331:18
  wire        _GEN_1 = io_dmaResp_valid & rDmaActive;	// C:\\Users\\admin\\.bazel\\2ryzlsy4\\execroot\\_main\\hdl\\chisel\\src\\accel\\npu\\NpuCore.scala:275:27, :383:29
  wire        _GEN_2 = rState == 3'h3;	// C:\\Users\\admin\\.bazel\\2ryzlsy4\\execroot\\_main\\hdl\\chisel\\src\\accel\\npu\\NpuCore.scala:261:25, :331:18
  wire        _GEN_3 = rState == 3'h4;	// C:\\Users\\admin\\.bazel\\2ryzlsy4\\execroot\\_main\\hdl\\chisel\\src\\accel\\npu\\NpuCore.scala:261:25, :331:18, :346:36
  always @(posedge clock) begin	// C:\\Users\\admin\\.bazel\\2ryzlsy4\\execroot\\_main\\hdl\\chisel\\src\\accel\\npu\\NpuCore.scala:190:7
    automatic logic _GEN_4;	// C:\\Users\\admin\\.bazel\\2ryzlsy4\\execroot\\_main\\hdl\\chisel\\src\\accel\\npu\\NpuCore.scala:262:21, :331:18, :334:26, :335:15
    _GEN_4 = ~(|rState) & io_cmd_valid;	// C:\\Users\\admin\\.bazel\\2ryzlsy4\\execroot\\_main\\hdl\\chisel\\src\\accel\\npu\\NpuCore.scala:261:25, :262:21, :311:26, :331:18, :334:26, :335:15
    if (reset) begin	// C:\\Users\\admin\\.bazel\\2ryzlsy4\\execroot\\_main\\hdl\\chisel\\src\\accel\\npu\\NpuCore.scala:190:7
      rState <= 3'h0;	// C:\\Users\\admin\\.bazel\\2ryzlsy4\\execroot\\_main\\hdl\\chisel\\src\\accel\\npu\\NpuCore.scala:261:25
      rDimM <= 16'h0;	// C:\\Users\\admin\\.bazel\\2ryzlsy4\\execroot\\_main\\hdl\\chisel\\src\\accel\\npu\\NpuCore.scala:263:25
      rDimN <= 16'h0;	// C:\\Users\\admin\\.bazel\\2ryzlsy4\\execroot\\_main\\hdl\\chisel\\src\\accel\\npu\\NpuCore.scala:264:25
      rDimK <= 16'h0;	// C:\\Users\\admin\\.bazel\\2ryzlsy4\\execroot\\_main\\hdl\\chisel\\src\\accel\\npu\\NpuCore.scala:265:25
      rRowIdx <= 16'h0;	// C:\\Users\\admin\\.bazel\\2ryzlsy4\\execroot\\_main\\hdl\\chisel\\src\\accel\\npu\\NpuCore.scala:266:25
      rColIdx <= 16'h0;	// C:\\Users\\admin\\.bazel\\2ryzlsy4\\execroot\\_main\\hdl\\chisel\\src\\accel\\npu\\NpuCore.scala:267:25
      rPhase <= 2'h0;	// C:\\Users\\admin\\.bazel\\2ryzlsy4\\execroot\\_main\\hdl\\chisel\\src\\accel\\npu\\NpuCore.scala:268:25
      rDmaActive <= 1'h0;	// C:\\Users\\admin\\.bazel\\2ryzlsy4\\execroot\\_main\\hdl\\chisel\\src\\accel\\npu\\NpuCore.scala:275:27
    end
    else begin	// C:\\Users\\admin\\.bazel\\2ryzlsy4\\execroot\\_main\\hdl\\chisel\\src\\accel\\npu\\NpuCore.scala:190:7
      if (|rState) begin	// C:\\Users\\admin\\.bazel\\2ryzlsy4\\execroot\\_main\\hdl\\chisel\\src\\accel\\npu\\NpuCore.scala:261:25, :311:26
        automatic logic            _GEN_5;	// C:\\Users\\admin\\.bazel\\2ryzlsy4\\execroot\\_main\\hdl\\chisel\\src\\accel\\npu\\NpuCore.scala:275:27, :375:29, :376:20
        automatic logic [15:0]     _rColIdx_T;	// C:\\Users\\admin\\.bazel\\2ryzlsy4\\execroot\\_main\\hdl\\chisel\\src\\accel\\npu\\NpuCore.scala:449:26
        automatic logic            _GEN_6;	// C:\\Users\\admin\\.bazel\\2ryzlsy4\\execroot\\_main\\hdl\\chisel\\src\\accel\\npu\\NpuCore.scala:450:26
        automatic logic            _GEN_7 = _GEN | _GEN_0;	// C:\\Users\\admin\\.bazel\\2ryzlsy4\\execroot\\_main\\hdl\\chisel\\src\\accel\\npu\\NpuCore.scala:267:25, :331:18
        automatic logic [15:0]     _rRowIdx_T;	// C:\\Users\\admin\\.bazel\\2ryzlsy4\\execroot\\_main\\hdl\\chisel\\src\\accel\\npu\\NpuCore.scala:452:28
        automatic logic            _GEN_8;	// C:\\Users\\admin\\.bazel\\2ryzlsy4\\execroot\\_main\\hdl\\chisel\\src\\accel\\npu\\NpuCore.scala:331:18
        automatic logic            _GEN_9;	// C:\\Users\\admin\\.bazel\\2ryzlsy4\\execroot\\_main\\hdl\\chisel\\src\\accel\\npu\\NpuCore.scala:275:27, :331:18, :491:44, :492:20
        automatic logic [2:0]      _GEN_10;	// C:\\Users\\admin\\.bazel\\2ryzlsy4\\execroot\\_main\\hdl\\chisel\\src\\accel\\npu\\NpuCore.scala:331:18, :501:25
        automatic logic [7:0][2:0] _GEN_11;	// C:\\Users\\admin\\.bazel\\2ryzlsy4\\execroot\\_main\\hdl\\chisel\\src\\accel\\npu\\NpuCore.scala:331:18, :375:29, :403:45, :450:36, :462:48, :483:29
        automatic logic [7:0]      _GEN_12;	// C:\\Users\\admin\\.bazel\\2ryzlsy4\\execroot\\_main\\hdl\\chisel\\src\\accel\\npu\\NpuCore.scala:275:27, :314:19, :331:18, :375:29, :383:44, :483:29
        _GEN_5 = io_dmaReq_ready | rDmaActive;	// C:\\Users\\admin\\.bazel\\2ryzlsy4\\execroot\\_main\\hdl\\chisel\\src\\accel\\npu\\NpuCore.scala:275:27, :375:29, :376:20
        _rColIdx_T = rColIdx + 16'h1;	// C:\\Users\\admin\\.bazel\\2ryzlsy4\\execroot\\_main\\hdl\\chisel\\src\\accel\\npu\\NpuCore.scala:267:25, :449:26
        _GEN_6 = _rColIdx_T >= rDimK;	// C:\\Users\\admin\\.bazel\\2ryzlsy4\\execroot\\_main\\hdl\\chisel\\src\\accel\\npu\\NpuCore.scala:265:25, :449:26, :450:26
        _rRowIdx_T = rRowIdx + 16'h1;	// C:\\Users\\admin\\.bazel\\2ryzlsy4\\execroot\\_main\\hdl\\chisel\\src\\accel\\npu\\NpuCore.scala:266:25, :452:28
        _GEN_8 = rState == 3'h6;	// C:\\Users\\admin\\.bazel\\2ryzlsy4\\execroot\\_main\\hdl\\chisel\\src\\accel\\npu\\NpuCore.scala:261:25, :304:31, :331:18
        _GEN_9 = ~(_GEN_8 & _GEN_1) & rDmaActive;	// C:\\Users\\admin\\.bazel\\2ryzlsy4\\execroot\\_main\\hdl\\chisel\\src\\accel\\npu\\NpuCore.scala:275:27, :331:18, :383:29, :491:44, :492:20
        _GEN_10 = (_GEN_8 ? ~rDmaActive | _GEN_1 : (&rState)) ? 3'h0 : rState;	// C:\\Users\\admin\\.bazel\\2ryzlsy4\\execroot\\_main\\hdl\\chisel\\src\\accel\\npu\\NpuCore.scala:261:25, :275:27, :331:18, :383:29, :403:32, :491:44, :493:37, :501:25, :502:16, :508:14
        _GEN_11 =
          {{_GEN_10},
           {_GEN_10},
           {io_dmaReq_ready ? 3'h6 : rState},
           {(&rPhase) ? 3'h5 : rState},
           {_GEN_6 & _rRowIdx_T >= rDimM ? 3'h4 : rState},
           {io_dmaResp_valid & ~rDmaActive ? 3'h3 : rState},
           {io_dmaReq_ready ? 3'h2 : rState},
           {_GEN_10}};	// C:\\Users\\admin\\.bazel\\2ryzlsy4\\execroot\\_main\\hdl\\chisel\\src\\accel\\npu\\NpuCore.scala:261:25, :263:25, :268:25, :275:27, :304:31, :331:18, :346:36, :375:29, :377:20, :383:44, :403:{29,32,45}, :404:37, :450:{26,36}, :452:28, :453:{28,38}, :454:18, :462:{19,48}, :470:16, :483:29, :485:20, :501:25
        rState <= _GEN_11[rState];	// C:\\Users\\admin\\.bazel\\2ryzlsy4\\execroot\\_main\\hdl\\chisel\\src\\accel\\npu\\NpuCore.scala:261:25, :331:18, :375:29, :403:45, :450:36, :462:48, :483:29
        if (_GEN_7 | ~(_GEN_2 & _GEN_6)) begin	// C:\\Users\\admin\\.bazel\\2ryzlsy4\\execroot\\_main\\hdl\\chisel\\src\\accel\\npu\\NpuCore.scala:266:25, :267:25, :331:18, :450:{26,36}, :452:17
        end
        else	// C:\\Users\\admin\\.bazel\\2ryzlsy4\\execroot\\_main\\hdl\\chisel\\src\\accel\\npu\\NpuCore.scala:266:25, :331:18
          rRowIdx <= _rRowIdx_T;	// C:\\Users\\admin\\.bazel\\2ryzlsy4\\execroot\\_main\\hdl\\chisel\\src\\accel\\npu\\NpuCore.scala:266:25, :452:28
        if (_GEN_7 | ~_GEN_2) begin	// C:\\Users\\admin\\.bazel\\2ryzlsy4\\execroot\\_main\\hdl\\chisel\\src\\accel\\npu\\NpuCore.scala:267:25, :331:18
        end
        else	// C:\\Users\\admin\\.bazel\\2ryzlsy4\\execroot\\_main\\hdl\\chisel\\src\\accel\\npu\\NpuCore.scala:267:25, :331:18
          rColIdx <= _GEN_6 ? 16'h0 : _rColIdx_T;	// C:\\Users\\admin\\.bazel\\2ryzlsy4\\execroot\\_main\\hdl\\chisel\\src\\accel\\npu\\NpuCore.scala:267:25, :449:{15,26}, :450:{26,36}, :451:17
        if (_GEN | _GEN_0 | _GEN_2 | ~_GEN_3) begin	// C:\\Users\\admin\\.bazel\\2ryzlsy4\\execroot\\_main\\hdl\\chisel\\src\\accel\\npu\\NpuCore.scala:268:25, :331:18
        end
        else	// C:\\Users\\admin\\.bazel\\2ryzlsy4\\execroot\\_main\\hdl\\chisel\\src\\accel\\npu\\NpuCore.scala:268:25, :331:18
          rPhase <= rPhase + 2'h1;	// C:\\Users\\admin\\.bazel\\2ryzlsy4\\execroot\\_main\\hdl\\chisel\\src\\accel\\npu\\NpuCore.scala:268:25, :461:24
        _GEN_12 =
          {{_GEN_9},
           {_GEN_9},
           {_GEN_5},
           {rDmaActive},
           {rDmaActive},
           {_GEN_1 ? io_dmaReq_ready : rDmaActive},
           {_GEN_5},
           {_GEN_9}};	// C:\\Users\\admin\\.bazel\\2ryzlsy4\\execroot\\_main\\hdl\\chisel\\src\\accel\\npu\\NpuCore.scala:275:27, :314:19, :331:18, :375:29, :376:20, :383:{29,44}, :385:37, :483:29, :491:44, :492:20
        rDmaActive <= _GEN_12[rState];	// C:\\Users\\admin\\.bazel\\2ryzlsy4\\execroot\\_main\\hdl\\chisel\\src\\accel\\npu\\NpuCore.scala:261:25, :275:27, :314:19, :331:18, :375:29, :383:44, :483:29
      end
      else if (io_cmd_valid) begin	// C:\\Users\\admin\\.bazel\\2ryzlsy4\\execroot\\_main\\hdl\\chisel\\src\\accel\\npu\\NpuCore.scala:191:14
        if (io_cmd_bits_opcode == 3'h1 | io_cmd_bits_opcode == 3'h2
            | io_cmd_bits_opcode == 3'h4)	// C:\\Users\\admin\\.bazel\\2ryzlsy4\\execroot\\_main\\hdl\\chisel\\src\\accel\\npu\\NpuCore.scala:346:36, :348:20, :351:20, :354:20, :461:24
          rState <= 3'h1;	// C:\\Users\\admin\\.bazel\\2ryzlsy4\\execroot\\_main\\hdl\\chisel\\src\\accel\\npu\\NpuCore.scala:261:25, :461:24
        else if (io_cmd_bits_opcode == 3'h5)	// C:\\Users\\admin\\.bazel\\2ryzlsy4\\execroot\\_main\\hdl\\chisel\\src\\accel\\npu\\NpuCore.scala:346:36
          rState <= 3'h5;	// C:\\Users\\admin\\.bazel\\2ryzlsy4\\execroot\\_main\\hdl\\chisel\\src\\accel\\npu\\NpuCore.scala:261:25, :346:36
        else if (io_cmd_bits_opcode == 3'h3)	// C:\\Users\\admin\\.bazel\\2ryzlsy4\\execroot\\_main\\hdl\\chisel\\src\\accel\\npu\\NpuCore.scala:346:36
          rState <= 3'h1;	// C:\\Users\\admin\\.bazel\\2ryzlsy4\\execroot\\_main\\hdl\\chisel\\src\\accel\\npu\\NpuCore.scala:261:25, :461:24
        rRowIdx <= 16'h0;	// C:\\Users\\admin\\.bazel\\2ryzlsy4\\execroot\\_main\\hdl\\chisel\\src\\accel\\npu\\NpuCore.scala:266:25
        rColIdx <= 16'h0;	// C:\\Users\\admin\\.bazel\\2ryzlsy4\\execroot\\_main\\hdl\\chisel\\src\\accel\\npu\\NpuCore.scala:267:25
        rPhase <= 2'h0;	// C:\\Users\\admin\\.bazel\\2ryzlsy4\\execroot\\_main\\hdl\\chisel\\src\\accel\\npu\\NpuCore.scala:268:25
      end
      if (_GEN_4) begin	// C:\\Users\\admin\\.bazel\\2ryzlsy4\\execroot\\_main\\hdl\\chisel\\src\\accel\\npu\\NpuCore.scala:262:21, :331:18, :334:26, :335:15
        rDimM <= io_cmd_bits_dimM;	// C:\\Users\\admin\\.bazel\\2ryzlsy4\\execroot\\_main\\hdl\\chisel\\src\\accel\\npu\\NpuCore.scala:263:25
        rDimN <= io_cmd_bits_dimN;	// C:\\Users\\admin\\.bazel\\2ryzlsy4\\execroot\\_main\\hdl\\chisel\\src\\accel\\npu\\NpuCore.scala:264:25
        rDimK <= io_cmd_bits_dimK;	// C:\\Users\\admin\\.bazel\\2ryzlsy4\\execroot\\_main\\hdl\\chisel\\src\\accel\\npu\\NpuCore.scala:265:25
      end
    end
    if (_GEN_4) begin	// C:\\Users\\admin\\.bazel\\2ryzlsy4\\execroot\\_main\\hdl\\chisel\\src\\accel\\npu\\NpuCore.scala:262:21, :331:18, :334:26, :335:15
      rCmd_srcAddr <= io_cmd_bits_srcAddr;	// C:\\Users\\admin\\.bazel\\2ryzlsy4\\execroot\\_main\\hdl\\chisel\\src\\accel\\npu\\NpuCore.scala:262:21
      rCmd_dstAddr <= io_cmd_bits_dstAddr;	// C:\\Users\\admin\\.bazel\\2ryzlsy4\\execroot\\_main\\hdl\\chisel\\src\\accel\\npu\\NpuCore.scala:262:21
    end
  end // always @(posedge)
  `ifdef ENABLE_INITIAL_REG_	// C:\\Users\\admin\\.bazel\\2ryzlsy4\\execroot\\_main\\hdl\\chisel\\src\\accel\\npu\\NpuCore.scala:190:7
    `ifdef FIRRTL_BEFORE_INITIAL	// C:\\Users\\admin\\.bazel\\2ryzlsy4\\execroot\\_main\\hdl\\chisel\\src\\accel\\npu\\NpuCore.scala:190:7
      `FIRRTL_BEFORE_INITIAL	// C:\\Users\\admin\\.bazel\\2ryzlsy4\\execroot\\_main\\hdl\\chisel\\src\\accel\\npu\\NpuCore.scala:190:7
    `endif // FIRRTL_BEFORE_INITIAL
    initial begin	// C:\\Users\\admin\\.bazel\\2ryzlsy4\\execroot\\_main\\hdl\\chisel\\src\\accel\\npu\\NpuCore.scala:190:7
      automatic logic [31:0] _RANDOM[0:26];	// C:\\Users\\admin\\.bazel\\2ryzlsy4\\execroot\\_main\\hdl\\chisel\\src\\accel\\npu\\NpuCore.scala:190:7
      `ifdef INIT_RANDOM_PROLOG_	// C:\\Users\\admin\\.bazel\\2ryzlsy4\\execroot\\_main\\hdl\\chisel\\src\\accel\\npu\\NpuCore.scala:190:7
        `INIT_RANDOM_PROLOG_	// C:\\Users\\admin\\.bazel\\2ryzlsy4\\execroot\\_main\\hdl\\chisel\\src\\accel\\npu\\NpuCore.scala:190:7
      `endif // INIT_RANDOM_PROLOG_
      `ifdef RANDOMIZE_REG_INIT	// C:\\Users\\admin\\.bazel\\2ryzlsy4\\execroot\\_main\\hdl\\chisel\\src\\accel\\npu\\NpuCore.scala:190:7
        for (logic [4:0] i = 5'h0; i < 5'h1B; i += 5'h1) begin
          _RANDOM[i] = `RANDOM;	// C:\\Users\\admin\\.bazel\\2ryzlsy4\\execroot\\_main\\hdl\\chisel\\src\\accel\\npu\\NpuCore.scala:190:7
        end	// C:\\Users\\admin\\.bazel\\2ryzlsy4\\execroot\\_main\\hdl\\chisel\\src\\accel\\npu\\NpuCore.scala:190:7
        rState = _RANDOM[5'h11][2:0];	// C:\\Users\\admin\\.bazel\\2ryzlsy4\\execroot\\_main\\hdl\\chisel\\src\\accel\\npu\\NpuCore.scala:190:7, :261:25
        rCmd_srcAddr = {_RANDOM[5'h11][31:7], _RANDOM[5'h12], _RANDOM[5'h13][6:0]};	// C:\\Users\\admin\\.bazel\\2ryzlsy4\\execroot\\_main\\hdl\\chisel\\src\\accel\\npu\\NpuCore.scala:190:7, :261:25, :262:21
        rCmd_dstAddr = {_RANDOM[5'h13][31:7], _RANDOM[5'h14], _RANDOM[5'h15][6:0]};	// C:\\Users\\admin\\.bazel\\2ryzlsy4\\execroot\\_main\\hdl\\chisel\\src\\accel\\npu\\NpuCore.scala:190:7, :262:21
        rDimM = {_RANDOM[5'h16][31], _RANDOM[5'h17][14:0]};	// C:\\Users\\admin\\.bazel\\2ryzlsy4\\execroot\\_main\\hdl\\chisel\\src\\accel\\npu\\NpuCore.scala:190:7, :263:25
        rDimN = _RANDOM[5'h17][30:15];	// C:\\Users\\admin\\.bazel\\2ryzlsy4\\execroot\\_main\\hdl\\chisel\\src\\accel\\npu\\NpuCore.scala:190:7, :263:25, :264:25
        rDimK = {_RANDOM[5'h17][31], _RANDOM[5'h18][14:0]};	// C:\\Users\\admin\\.bazel\\2ryzlsy4\\execroot\\_main\\hdl\\chisel\\src\\accel\\npu\\NpuCore.scala:190:7, :263:25, :265:25
        rRowIdx = _RANDOM[5'h18][30:15];	// C:\\Users\\admin\\.bazel\\2ryzlsy4\\execroot\\_main\\hdl\\chisel\\src\\accel\\npu\\NpuCore.scala:190:7, :265:25, :266:25
        rColIdx = {_RANDOM[5'h18][31], _RANDOM[5'h19][14:0]};	// C:\\Users\\admin\\.bazel\\2ryzlsy4\\execroot\\_main\\hdl\\chisel\\src\\accel\\npu\\NpuCore.scala:190:7, :265:25, :267:25
        rPhase = _RANDOM[5'h19][16:15];	// C:\\Users\\admin\\.bazel\\2ryzlsy4\\execroot\\_main\\hdl\\chisel\\src\\accel\\npu\\NpuCore.scala:190:7, :267:25, :268:25
        rDmaActive = _RANDOM[5'h1A][29];	// C:\\Users\\admin\\.bazel\\2ryzlsy4\\execroot\\_main\\hdl\\chisel\\src\\accel\\npu\\NpuCore.scala:190:7, :275:27
      `endif // RANDOMIZE_REG_INIT
    end // initial
    `ifdef FIRRTL_AFTER_INITIAL	// C:\\Users\\admin\\.bazel\\2ryzlsy4\\execroot\\_main\\hdl\\chisel\\src\\accel\\npu\\NpuCore.scala:190:7
      `FIRRTL_AFTER_INITIAL	// C:\\Users\\admin\\.bazel\\2ryzlsy4\\execroot\\_main\\hdl\\chisel\\src\\accel\\npu\\NpuCore.scala:190:7
    `endif // FIRRTL_AFTER_INITIAL
  `endif // ENABLE_INITIAL_REG_
  assign io_cmd_ready = ~(|rState);	// C:\\Users\\admin\\.bazel\\2ryzlsy4\\execroot\\_main\\hdl\\chisel\\src\\accel\\npu\\NpuCore.scala:190:7, :261:25, :311:26
  assign io_status_done = rState == 3'h6;	// C:\\Users\\admin\\.bazel\\2ryzlsy4\\execroot\\_main\\hdl\\chisel\\src\\accel\\npu\\NpuCore.scala:190:7, :261:25, :304:31
  assign io_status_error = &rState;	// C:\\Users\\admin\\.bazel\\2ryzlsy4\\execroot\\_main\\hdl\\chisel\\src\\accel\\npu\\NpuCore.scala:190:7, :261:25, :305:31
  assign io_dmaReq_valid =
    (|rState) & (_GEN | (_GEN_0 ? _GEN_1 : ~(_GEN_2 | _GEN_3) & rState == 3'h5));	// C:\\Users\\admin\\.bazel\\2ryzlsy4\\execroot\\_main\\hdl\\chisel\\src\\accel\\npu\\NpuCore.scala:190:7, :261:25, :311:26, :314:19, :331:18, :346:36, :368:28, :383:{29,44}
  assign io_dmaReq_bits_addr =
    _GEN
      ? rCmd_srcAddr
      : _GEN_0
          ? rCmd_srcAddr + {29'h0, {16'h0, rDimM} * {16'h0, rDimK}, 3'h0}
          : rCmd_dstAddr;	// C:\\Users\\admin\\.bazel\\2ryzlsy4\\execroot\\_main\\hdl\\chisel\\src\\accel\\npu\\NpuCore.scala:190:7, :262:21, :263:25, :265:25, :331:18, :370:28, :372:37, :383:44, :392:{48,57}
  assign io_dmaReq_bits_len =
    _GEN ? rDimM * rDimK : _GEN_0 ? rDimK * rDimN : rDimM * rDimN;	// C:\\Users\\admin\\.bazel\\2ryzlsy4\\execroot\\_main\\hdl\\chisel\\src\\accel\\npu\\NpuCore.scala:190:7, :263:25, :264:25, :265:25, :331:18, :372:{28,37}, :383:44, :394:41, :480:37
  assign io_dmaReq_bits_isLoad = _GEN | _GEN_0;	// C:\\Users\\admin\\.bazel\\2ryzlsy4\\execroot\\_main\\hdl\\chisel\\src\\accel\\npu\\NpuCore.scala:190:7, :331:18, :373:29
endmodule

module DmaEngine(	// C:\\Users\\admin\\.bazel\\2ryzlsy4\\execroot\\_main\\hdl\\chisel\\src\\accel\\npu\\DmaEngine.scala:54:7
  input         clock,	// C:\\Users\\admin\\.bazel\\2ryzlsy4\\execroot\\_main\\hdl\\chisel\\src\\accel\\npu\\DmaEngine.scala:54:7
                reset,	// C:\\Users\\admin\\.bazel\\2ryzlsy4\\execroot\\_main\\hdl\\chisel\\src\\accel\\npu\\DmaEngine.scala:54:7
  output        io_dmaReq_ready,	// C:\\Users\\admin\\.bazel\\2ryzlsy4\\execroot\\_main\\hdl\\chisel\\src\\accel\\npu\\DmaEngine.scala:59:14
  input         io_dmaReq_valid,	// C:\\Users\\admin\\.bazel\\2ryzlsy4\\execroot\\_main\\hdl\\chisel\\src\\accel\\npu\\DmaEngine.scala:59:14
  input  [63:0] io_dmaReq_bits_addr,	// C:\\Users\\admin\\.bazel\\2ryzlsy4\\execroot\\_main\\hdl\\chisel\\src\\accel\\npu\\DmaEngine.scala:59:14
  input  [15:0] io_dmaReq_bits_len,	// C:\\Users\\admin\\.bazel\\2ryzlsy4\\execroot\\_main\\hdl\\chisel\\src\\accel\\npu\\DmaEngine.scala:59:14
  input         io_dmaReq_bits_isLoad,	// C:\\Users\\admin\\.bazel\\2ryzlsy4\\execroot\\_main\\hdl\\chisel\\src\\accel\\npu\\DmaEngine.scala:59:14
  output        io_dmaResp_valid,	// C:\\Users\\admin\\.bazel\\2ryzlsy4\\execroot\\_main\\hdl\\chisel\\src\\accel\\npu\\DmaEngine.scala:59:14
  output [63:0] io_axiMaster_aw_addr,	// C:\\Users\\admin\\.bazel\\2ryzlsy4\\execroot\\_main\\hdl\\chisel\\src\\accel\\npu\\DmaEngine.scala:59:14
  output [7:0]  io_axiMaster_aw_len,	// C:\\Users\\admin\\.bazel\\2ryzlsy4\\execroot\\_main\\hdl\\chisel\\src\\accel\\npu\\DmaEngine.scala:59:14
  input         io_axiMaster_aw_ready,	// C:\\Users\\admin\\.bazel\\2ryzlsy4\\execroot\\_main\\hdl\\chisel\\src\\accel\\npu\\DmaEngine.scala:59:14
  output        io_axiMaster_w_last,	// C:\\Users\\admin\\.bazel\\2ryzlsy4\\execroot\\_main\\hdl\\chisel\\src\\accel\\npu\\DmaEngine.scala:59:14
  input         io_axiMaster_b_valid,	// C:\\Users\\admin\\.bazel\\2ryzlsy4\\execroot\\_main\\hdl\\chisel\\src\\accel\\npu\\DmaEngine.scala:59:14
  output        io_axiMaster_b_ready,	// C:\\Users\\admin\\.bazel\\2ryzlsy4\\execroot\\_main\\hdl\\chisel\\src\\accel\\npu\\DmaEngine.scala:59:14
  output [63:0] io_axiMaster_ar_addr,	// C:\\Users\\admin\\.bazel\\2ryzlsy4\\execroot\\_main\\hdl\\chisel\\src\\accel\\npu\\DmaEngine.scala:59:14
  output [7:0]  io_axiMaster_ar_len,	// C:\\Users\\admin\\.bazel\\2ryzlsy4\\execroot\\_main\\hdl\\chisel\\src\\accel\\npu\\DmaEngine.scala:59:14
  input         io_axiMaster_ar_ready,	// C:\\Users\\admin\\.bazel\\2ryzlsy4\\execroot\\_main\\hdl\\chisel\\src\\accel\\npu\\DmaEngine.scala:59:14
                io_axiMaster_r_last,	// C:\\Users\\admin\\.bazel\\2ryzlsy4\\execroot\\_main\\hdl\\chisel\\src\\accel\\npu\\DmaEngine.scala:59:14
                io_axiMaster_r_valid,	// C:\\Users\\admin\\.bazel\\2ryzlsy4\\execroot\\_main\\hdl\\chisel\\src\\accel\\npu\\DmaEngine.scala:59:14
  output        io_axiMaster_r_ready	// C:\\Users\\admin\\.bazel\\2ryzlsy4\\execroot\\_main\\hdl\\chisel\\src\\accel\\npu\\DmaEngine.scala:59:14
);

  reg  [2:0]  r_state;	// C:\\Users\\admin\\.bazel\\2ryzlsy4\\execroot\\_main\\hdl\\chisel\\src\\accel\\npu\\DmaEngine.scala:89:28
  reg  [63:0] r_srcAddr;	// C:\\Users\\admin\\.bazel\\2ryzlsy4\\execroot\\_main\\hdl\\chisel\\src\\accel\\npu\\DmaEngine.scala:90:28
  reg  [63:0] r_dstAddr;	// C:\\Users\\admin\\.bazel\\2ryzlsy4\\execroot\\_main\\hdl\\chisel\\src\\accel\\npu\\DmaEngine.scala:91:28
  reg  [15:0] r_xferLen;	// C:\\Users\\admin\\.bazel\\2ryzlsy4\\execroot\\_main\\hdl\\chisel\\src\\accel\\npu\\DmaEngine.scala:92:28
  reg  [15:0] r_beatCount;	// C:\\Users\\admin\\.bazel\\2ryzlsy4\\execroot\\_main\\hdl\\chisel\\src\\accel\\npu\\DmaEngine.scala:93:28
  wire        io_dmaReq_ready_0 = r_state == 3'h0;	// C:\\Users\\admin\\.bazel\\2ryzlsy4\\execroot\\_main\\hdl\\chisel\\src\\accel\\npu\\DmaEngine.scala:54:7, :89:28, :125:19
  wire        _GEN = r_state == 3'h1;	// C:\\Users\\admin\\.bazel\\2ryzlsy4\\execroot\\_main\\hdl\\chisel\\src\\accel\\npu\\DmaEngine.scala:54:7, :89:28, :125:19
  wire        _GEN_0 = r_state == 3'h2;	// C:\\Users\\admin\\.bazel\\2ryzlsy4\\execroot\\_main\\hdl\\chisel\\src\\accel\\npu\\DmaEngine.scala:54:7, :89:28, :125:19
  wire        _GEN_1 = r_state == 3'h3;	// C:\\Users\\admin\\.bazel\\2ryzlsy4\\execroot\\_main\\hdl\\chisel\\src\\accel\\npu\\DmaEngine.scala:54:7, :89:28, :125:19
  wire        _GEN_2 = r_state == 3'h4;	// C:\\Users\\admin\\.bazel\\2ryzlsy4\\execroot\\_main\\hdl\\chisel\\src\\accel\\npu\\DmaEngine.scala:54:7, :89:28, :125:19
  wire        _GEN_3 = r_state == 3'h5;	// C:\\Users\\admin\\.bazel\\2ryzlsy4\\execroot\\_main\\hdl\\chisel\\src\\accel\\npu\\DmaEngine.scala:54:7, :89:28, :125:19
  always @(posedge clock) begin	// C:\\Users\\admin\\.bazel\\2ryzlsy4\\execroot\\_main\\hdl\\chisel\\src\\accel\\npu\\DmaEngine.scala:54:7
    if (reset) begin	// C:\\Users\\admin\\.bazel\\2ryzlsy4\\execroot\\_main\\hdl\\chisel\\src\\accel\\npu\\DmaEngine.scala:54:7
      r_state <= 3'h0;	// C:\\Users\\admin\\.bazel\\2ryzlsy4\\execroot\\_main\\hdl\\chisel\\src\\accel\\npu\\DmaEngine.scala:54:7, :89:28
      r_srcAddr <= 64'h0;	// C:\\Users\\admin\\.bazel\\2ryzlsy4\\execroot\\_main\\hdl\\chisel\\src\\accel\\npu\\DmaEngine.scala:90:28
      r_dstAddr <= 64'h0;	// C:\\Users\\admin\\.bazel\\2ryzlsy4\\execroot\\_main\\hdl\\chisel\\src\\accel\\npu\\DmaEngine.scala:91:28
      r_xferLen <= 16'h0;	// C:\\Users\\admin\\.bazel\\2ryzlsy4\\execroot\\_main\\hdl\\chisel\\src\\accel\\npu\\DmaEngine.scala:92:28
      r_beatCount <= 16'h0;	// C:\\Users\\admin\\.bazel\\2ryzlsy4\\execroot\\_main\\hdl\\chisel\\src\\accel\\npu\\DmaEngine.scala:93:28
    end
    else begin	// C:\\Users\\admin\\.bazel\\2ryzlsy4\\execroot\\_main\\hdl\\chisel\\src\\accel\\npu\\DmaEngine.scala:54:7
      automatic logic [7:0][2:0] _GEN_4;	// C:\\Users\\admin\\.bazel\\2ryzlsy4\\execroot\\_main\\hdl\\chisel\\src\\accel\\npu\\DmaEngine.scala:89:28, :125:19, :128:29, :153:35, :161:53, :186:35, :201:52, :213:34, :224:30, :225:17
      _GEN_4 =
        {{r_state},
         {3'h0},
         {io_axiMaster_b_valid ? 3'h6 : r_state},
         {r_state},
         {io_axiMaster_aw_ready ? 3'h4 : r_state},
         {io_axiMaster_r_valid & io_axiMaster_r_last ? 3'h6 : r_state},
         {io_axiMaster_ar_ready ? 3'h2 : r_state},
         {io_dmaReq_valid ? {1'h0, ~io_dmaReq_bits_isLoad, 1'h1} : r_state}};	// C:\\Users\\admin\\.bazel\\2ryzlsy4\\execroot\\_main\\hdl\\chisel\\src\\accel\\npu\\DmaEngine.scala:54:7, :89:28, :125:19, :128:29, :139:{17,23}, :153:35, :154:17, :161:53, :167:35, :168:19, :186:35, :187:17, :201:52, :213:34, :214:17, :224:30, :225:17
      r_state <= _GEN_4[r_state];	// C:\\Users\\admin\\.bazel\\2ryzlsy4\\execroot\\_main\\hdl\\chisel\\src\\accel\\npu\\DmaEngine.scala:89:28, :125:19, :128:29, :153:35, :161:53, :186:35, :201:52, :213:34, :224:30, :225:17
      if (io_dmaReq_ready_0 & io_dmaReq_valid) begin	// C:\\Users\\admin\\.bazel\\2ryzlsy4\\execroot\\_main\\hdl\\chisel\\src\\accel\\npu\\DmaEngine.scala:92:28, :125:19, :128:29, :134:21
        r_srcAddr <= io_dmaReq_bits_isLoad ? io_dmaReq_bits_addr : 64'h0;	// C:\\Users\\admin\\.bazel\\2ryzlsy4\\execroot\\_main\\hdl\\chisel\\src\\accel\\npu\\DmaEngine.scala:90:28, :132:27
        r_xferLen <= io_dmaReq_bits_len;	// C:\\Users\\admin\\.bazel\\2ryzlsy4\\execroot\\_main\\hdl\\chisel\\src\\accel\\npu\\DmaEngine.scala:92:28
      end
      if (io_dmaReq_ready_0) begin	// C:\\Users\\admin\\.bazel\\2ryzlsy4\\execroot\\_main\\hdl\\chisel\\src\\accel\\npu\\DmaEngine.scala:125:19
        if (io_dmaReq_valid) begin	// C:\\Users\\admin\\.bazel\\2ryzlsy4\\execroot\\_main\\hdl\\chisel\\src\\accel\\npu\\DmaEngine.scala:59:14
          r_dstAddr <= io_dmaReq_bits_isLoad ? 64'h0 : io_dmaReq_bits_addr;	// C:\\Users\\admin\\.bazel\\2ryzlsy4\\execroot\\_main\\hdl\\chisel\\src\\accel\\npu\\DmaEngine.scala:91:28, :133:27
          r_beatCount <= 16'h0;	// C:\\Users\\admin\\.bazel\\2ryzlsy4\\execroot\\_main\\hdl\\chisel\\src\\accel\\npu\\DmaEngine.scala:93:28
        end
      end
      else if (_GEN | ~(_GEN_0 & io_axiMaster_r_valid)) begin	// C:\\Users\\admin\\.bazel\\2ryzlsy4\\execroot\\_main\\hdl\\chisel\\src\\accel\\npu\\DmaEngine.scala:91:28, :93:28, :125:19, :161:53, :166:21
      end
      else begin	// C:\\Users\\admin\\.bazel\\2ryzlsy4\\execroot\\_main\\hdl\\chisel\\src\\accel\\npu\\DmaEngine.scala:93:28, :125:19
        r_dstAddr <= r_dstAddr + 64'h1;	// C:\\Users\\admin\\.bazel\\2ryzlsy4\\execroot\\_main\\hdl\\chisel\\src\\accel\\npu\\DmaEngine.scala:91:28, :166:34
        r_beatCount <= r_beatCount + 16'h1;	// C:\\Users\\admin\\.bazel\\2ryzlsy4\\execroot\\_main\\hdl\\chisel\\src\\accel\\npu\\DmaEngine.scala:93:28, :165:36
      end
    end
  end // always @(posedge)
  `ifdef ENABLE_INITIAL_REG_	// C:\\Users\\admin\\.bazel\\2ryzlsy4\\execroot\\_main\\hdl\\chisel\\src\\accel\\npu\\DmaEngine.scala:54:7
    `ifdef FIRRTL_BEFORE_INITIAL	// C:\\Users\\admin\\.bazel\\2ryzlsy4\\execroot\\_main\\hdl\\chisel\\src\\accel\\npu\\DmaEngine.scala:54:7
      `FIRRTL_BEFORE_INITIAL	// C:\\Users\\admin\\.bazel\\2ryzlsy4\\execroot\\_main\\hdl\\chisel\\src\\accel\\npu\\DmaEngine.scala:54:7
    `endif // FIRRTL_BEFORE_INITIAL
    initial begin	// C:\\Users\\admin\\.bazel\\2ryzlsy4\\execroot\\_main\\hdl\\chisel\\src\\accel\\npu\\DmaEngine.scala:54:7
      automatic logic [31:0] _RANDOM[0:5];	// C:\\Users\\admin\\.bazel\\2ryzlsy4\\execroot\\_main\\hdl\\chisel\\src\\accel\\npu\\DmaEngine.scala:54:7
      `ifdef INIT_RANDOM_PROLOG_	// C:\\Users\\admin\\.bazel\\2ryzlsy4\\execroot\\_main\\hdl\\chisel\\src\\accel\\npu\\DmaEngine.scala:54:7
        `INIT_RANDOM_PROLOG_	// C:\\Users\\admin\\.bazel\\2ryzlsy4\\execroot\\_main\\hdl\\chisel\\src\\accel\\npu\\DmaEngine.scala:54:7
      `endif // INIT_RANDOM_PROLOG_
      `ifdef RANDOMIZE_REG_INIT	// C:\\Users\\admin\\.bazel\\2ryzlsy4\\execroot\\_main\\hdl\\chisel\\src\\accel\\npu\\DmaEngine.scala:54:7
        for (logic [2:0] i = 3'h0; i < 3'h6; i += 3'h1) begin
          _RANDOM[i] = `RANDOM;	// C:\\Users\\admin\\.bazel\\2ryzlsy4\\execroot\\_main\\hdl\\chisel\\src\\accel\\npu\\DmaEngine.scala:54:7
        end	// C:\\Users\\admin\\.bazel\\2ryzlsy4\\execroot\\_main\\hdl\\chisel\\src\\accel\\npu\\DmaEngine.scala:54:7
        r_state = _RANDOM[3'h0][2:0];	// C:\\Users\\admin\\.bazel\\2ryzlsy4\\execroot\\_main\\hdl\\chisel\\src\\accel\\npu\\DmaEngine.scala:54:7, :89:28
        r_srcAddr = {_RANDOM[3'h0][31:3], _RANDOM[3'h1], _RANDOM[3'h2][2:0]};	// C:\\Users\\admin\\.bazel\\2ryzlsy4\\execroot\\_main\\hdl\\chisel\\src\\accel\\npu\\DmaEngine.scala:54:7, :89:28, :90:28
        r_dstAddr = {_RANDOM[3'h2][31:3], _RANDOM[3'h3], _RANDOM[3'h4][2:0]};	// C:\\Users\\admin\\.bazel\\2ryzlsy4\\execroot\\_main\\hdl\\chisel\\src\\accel\\npu\\DmaEngine.scala:54:7, :90:28, :91:28
        r_xferLen = _RANDOM[3'h4][18:3];	// C:\\Users\\admin\\.bazel\\2ryzlsy4\\execroot\\_main\\hdl\\chisel\\src\\accel\\npu\\DmaEngine.scala:54:7, :91:28, :92:28
        r_beatCount = {_RANDOM[3'h4][31:19], _RANDOM[3'h5][2:0]};	// C:\\Users\\admin\\.bazel\\2ryzlsy4\\execroot\\_main\\hdl\\chisel\\src\\accel\\npu\\DmaEngine.scala:54:7, :91:28, :93:28
      `endif // RANDOMIZE_REG_INIT
    end // initial
    `ifdef FIRRTL_AFTER_INITIAL	// C:\\Users\\admin\\.bazel\\2ryzlsy4\\execroot\\_main\\hdl\\chisel\\src\\accel\\npu\\DmaEngine.scala:54:7
      `FIRRTL_AFTER_INITIAL	// C:\\Users\\admin\\.bazel\\2ryzlsy4\\execroot\\_main\\hdl\\chisel\\src\\accel\\npu\\DmaEngine.scala:54:7
    `endif // FIRRTL_AFTER_INITIAL
  `endif // ENABLE_INITIAL_REG_
  assign io_dmaReq_ready = io_dmaReq_ready_0;	// C:\\Users\\admin\\.bazel\\2ryzlsy4\\execroot\\_main\\hdl\\chisel\\src\\accel\\npu\\DmaEngine.scala:54:7, :125:19
  assign io_dmaResp_valid =
    ~(io_dmaReq_ready_0 | _GEN | _GEN_0 | _GEN_1 | _GEN_2 | _GEN_3) & r_state == 3'h6;	// C:\\Users\\admin\\.bazel\\2ryzlsy4\\execroot\\_main\\hdl\\chisel\\src\\accel\\npu\\DmaEngine.scala:54:7, :89:28, :113:20, :125:19
  assign io_axiMaster_aw_addr = r_dstAddr;	// C:\\Users\\admin\\.bazel\\2ryzlsy4\\execroot\\_main\\hdl\\chisel\\src\\accel\\npu\\DmaEngine.scala:54:7, :91:28
  assign io_axiMaster_aw_len = (r_xferLen > 16'h100 ? 8'h0 : r_xferLen[7:0]) - 8'h1;	// C:\\Users\\admin\\.bazel\\2ryzlsy4\\execroot\\_main\\hdl\\chisel\\src\\accel\\npu\\DmaEngine.scala:54:7, :92:28, :148:36, :177:{25,36}, :178:41
  assign io_axiMaster_w_last = r_beatCount + 16'h1 >= r_xferLen;	// C:\\Users\\admin\\.bazel\\2ryzlsy4\\execroot\\_main\\hdl\\chisel\\src\\accel\\npu\\DmaEngine.scala:54:7, :92:28, :93:28, :195:{43,49}
  assign io_axiMaster_b_ready =
    ~(io_dmaReq_ready_0 | _GEN | _GEN_0 | _GEN_1 | _GEN_2) & _GEN_3;	// C:\\Users\\admin\\.bazel\\2ryzlsy4\\execroot\\_main\\hdl\\chisel\\src\\accel\\npu\\DmaEngine.scala:54:7, :106:25, :125:19
  assign io_axiMaster_ar_addr = r_srcAddr;	// C:\\Users\\admin\\.bazel\\2ryzlsy4\\execroot\\_main\\hdl\\chisel\\src\\accel\\npu\\DmaEngine.scala:54:7, :90:28
  assign io_axiMaster_ar_len = (r_xferLen > 16'h100 ? 8'h0 : r_xferLen[7:0]) - 8'h1;	// C:\\Users\\admin\\.bazel\\2ryzlsy4\\execroot\\_main\\hdl\\chisel\\src\\accel\\npu\\DmaEngine.scala:54:7, :92:28, :148:{25,36}, :149:41
  assign io_axiMaster_r_ready = ~(io_dmaReq_ready_0 | _GEN) & _GEN_0;	// C:\\Users\\admin\\.bazel\\2ryzlsy4\\execroot\\_main\\hdl\\chisel\\src\\accel\\npu\\DmaEngine.scala:54:7, :109:25, :125:19
endmodule

module MmaEngine(	// C:\\Users\\admin\\.bazel\\2ryzlsy4\\execroot\\_main\\hdl\\chisel\\src\\accel\\npu\\MmaEngine.scala:120:7
  input  clock,	// C:\\Users\\admin\\.bazel\\2ryzlsy4\\execroot\\_main\\hdl\\chisel\\src\\accel\\npu\\MmaEngine.scala:120:7
         reset,	// C:\\Users\\admin\\.bazel\\2ryzlsy4\\execroot\\_main\\hdl\\chisel\\src\\accel\\npu\\MmaEngine.scala:120:7
         io_cmdValid,	// C:\\Users\\admin\\.bazel\\2ryzlsy4\\execroot\\_main\\hdl\\chisel\\src\\accel\\npu\\MmaEngine.scala:126:14
         io_cWriteReady,	// C:\\Users\\admin\\.bazel\\2ryzlsy4\\execroot\\_main\\hdl\\chisel\\src\\accel\\npu\\MmaEngine.scala:126:14
  output io_busy,	// C:\\Users\\admin\\.bazel\\2ryzlsy4\\execroot\\_main\\hdl\\chisel\\src\\accel\\npu\\MmaEngine.scala:126:14
         io_done	// C:\\Users\\admin\\.bazel\\2ryzlsy4\\execroot\\_main\\hdl\\chisel\\src\\accel\\npu\\MmaEngine.scala:126:14
);

  reg [2:0]  r_state;	// C:\\Users\\admin\\.bazel\\2ryzlsy4\\execroot\\_main\\hdl\\chisel\\src\\accel\\npu\\MmaEngine.scala:183:29
  reg [15:0] r_mBlockIdx;	// C:\\Users\\admin\\.bazel\\2ryzlsy4\\execroot\\_main\\hdl\\chisel\\src\\accel\\npu\\MmaEngine.scala:187:29
  reg [15:0] r_nBlockIdx;	// C:\\Users\\admin\\.bazel\\2ryzlsy4\\execroot\\_main\\hdl\\chisel\\src\\accel\\npu\\MmaEngine.scala:188:29
  reg [15:0] r_kBlockIdx;	// C:\\Users\\admin\\.bazel\\2ryzlsy4\\execroot\\_main\\hdl\\chisel\\src\\accel\\npu\\MmaEngine.scala:189:29
  always @(posedge clock) begin	// C:\\Users\\admin\\.bazel\\2ryzlsy4\\execroot\\_main\\hdl\\chisel\\src\\accel\\npu\\MmaEngine.scala:120:7
    if (reset) begin	// C:\\Users\\admin\\.bazel\\2ryzlsy4\\execroot\\_main\\hdl\\chisel\\src\\accel\\npu\\MmaEngine.scala:120:7
      r_state <= 3'h0;	// C:\\Users\\admin\\.bazel\\2ryzlsy4\\execroot\\_main\\hdl\\chisel\\src\\accel\\npu\\MmaEngine.scala:120:7, :183:29
      r_mBlockIdx <= 16'h0;	// C:\\Users\\admin\\.bazel\\2ryzlsy4\\execroot\\_main\\hdl\\chisel\\src\\accel\\npu\\MmaEngine.scala:187:29
      r_nBlockIdx <= 16'h0;	// C:\\Users\\admin\\.bazel\\2ryzlsy4\\execroot\\_main\\hdl\\chisel\\src\\accel\\npu\\MmaEngine.scala:188:29
      r_kBlockIdx <= 16'h0;	// C:\\Users\\admin\\.bazel\\2ryzlsy4\\execroot\\_main\\hdl\\chisel\\src\\accel\\npu\\MmaEngine.scala:189:29
    end
    else begin	// C:\\Users\\admin\\.bazel\\2ryzlsy4\\execroot\\_main\\hdl\\chisel\\src\\accel\\npu\\MmaEngine.scala:120:7
      automatic logic            _GEN;	// C:\\Users\\admin\\.bazel\\2ryzlsy4\\execroot\\_main\\hdl\\chisel\\src\\accel\\npu\\MmaEngine.scala:303:24
      automatic logic            _GEN_0;	// C:\\Users\\admin\\.bazel\\2ryzlsy4\\execroot\\_main\\hdl\\chisel\\src\\accel\\npu\\MmaEngine.scala:311:30
      automatic logic            _GEN_1;	// C:\\Users\\admin\\.bazel\\2ryzlsy4\\execroot\\_main\\hdl\\chisel\\src\\accel\\npu\\MmaEngine.scala:324:30
      automatic logic            _GEN_2;	// C:\\Users\\admin\\.bazel\\2ryzlsy4\\execroot\\_main\\hdl\\chisel\\src\\accel\\npu\\MmaEngine.scala:187:29, :303:43, :311:49, :324:49
      automatic logic [7:0][2:0] _GEN_3;	// C:\\Users\\admin\\.bazel\\2ryzlsy4\\execroot\\_main\\hdl\\chisel\\src\\accel\\npu\\MmaEngine.scala:183:29, :227:19, :229:25, :259:15, :265:44, :293:28, :303:43, :345:15
      _GEN = r_kBlockIdx != 16'hFFFF;	// C:\\Users\\admin\\.bazel\\2ryzlsy4\\execroot\\_main\\hdl\\chisel\\src\\accel\\npu\\MmaEngine.scala:189:29, :303:24
      _GEN_0 = r_nBlockIdx != 16'hFFFF;	// C:\\Users\\admin\\.bazel\\2ryzlsy4\\execroot\\_main\\hdl\\chisel\\src\\accel\\npu\\MmaEngine.scala:188:29, :311:30
      _GEN_1 = r_mBlockIdx != 16'hFFFF;	// C:\\Users\\admin\\.bazel\\2ryzlsy4\\execroot\\_main\\hdl\\chisel\\src\\accel\\npu\\MmaEngine.scala:187:29, :324:30
      _GEN_2 = _GEN | _GEN_0;	// C:\\Users\\admin\\.bazel\\2ryzlsy4\\execroot\\_main\\hdl\\chisel\\src\\accel\\npu\\MmaEngine.scala:187:29, :303:{24,43}, :311:{30,49}, :324:49
      _GEN_3 =
        {{r_state},
         {r_state},
         {3'h0},
         {{~(_GEN_2 | _GEN_1), 2'h1}},
         {io_cWriteReady ? 3'h4 : r_state},
         {r_state},
         {3'h2},
         {io_cmdValid ? 3'h1 : r_state}};	// C:\\Users\\admin\\.bazel\\2ryzlsy4\\execroot\\_main\\hdl\\chisel\\src\\accel\\npu\\MmaEngine.scala:120:7, :183:29, :187:29, :227:19, :229:25, :230:17, :259:15, :265:44, :293:28, :295:17, :303:43, :310:17, :311:49, :323:17, :324:{30,49}, :337:17, :340:17, :345:15
      r_state <= _GEN_3[r_state];	// C:\\Users\\admin\\.bazel\\2ryzlsy4\\execroot\\_main\\hdl\\chisel\\src\\accel\\npu\\MmaEngine.scala:183:29, :227:19, :229:25, :259:15, :265:44, :293:28, :303:43, :345:15
      if (r_state == 3'h0) begin	// C:\\Users\\admin\\.bazel\\2ryzlsy4\\execroot\\_main\\hdl\\chisel\\src\\accel\\npu\\MmaEngine.scala:120:7, :183:29, :227:19
        if (io_cmdValid) begin	// C:\\Users\\admin\\.bazel\\2ryzlsy4\\execroot\\_main\\hdl\\chisel\\src\\accel\\npu\\MmaEngine.scala:126:14
          r_mBlockIdx <= 16'h0;	// C:\\Users\\admin\\.bazel\\2ryzlsy4\\execroot\\_main\\hdl\\chisel\\src\\accel\\npu\\MmaEngine.scala:187:29
          r_nBlockIdx <= 16'h0;	// C:\\Users\\admin\\.bazel\\2ryzlsy4\\execroot\\_main\\hdl\\chisel\\src\\accel\\npu\\MmaEngine.scala:188:29
          r_kBlockIdx <= 16'h0;	// C:\\Users\\admin\\.bazel\\2ryzlsy4\\execroot\\_main\\hdl\\chisel\\src\\accel\\npu\\MmaEngine.scala:189:29
        end
      end
      else begin	// C:\\Users\\admin\\.bazel\\2ryzlsy4\\execroot\\_main\\hdl\\chisel\\src\\accel\\npu\\MmaEngine.scala:227:19
        automatic logic _GEN_4;	// C:\\Users\\admin\\.bazel\\2ryzlsy4\\execroot\\_main\\hdl\\chisel\\src\\accel\\npu\\MmaEngine.scala:227:19
        automatic logic _GEN_5;	// C:\\Users\\admin\\.bazel\\2ryzlsy4\\execroot\\_main\\hdl\\chisel\\src\\accel\\npu\\MmaEngine.scala:187:29, :227:19
        _GEN_4 = r_state != 3'h4;	// C:\\Users\\admin\\.bazel\\2ryzlsy4\\execroot\\_main\\hdl\\chisel\\src\\accel\\npu\\MmaEngine.scala:120:7, :183:29, :227:19
        _GEN_5 = r_state == 3'h1 | r_state == 3'h2 | r_state == 3'h3;	// C:\\Users\\admin\\.bazel\\2ryzlsy4\\execroot\\_main\\hdl\\chisel\\src\\accel\\npu\\MmaEngine.scala:120:7, :183:29, :187:29, :227:19
        if (_GEN_5 | _GEN_4 | _GEN_2 | ~_GEN_1) begin	// C:\\Users\\admin\\.bazel\\2ryzlsy4\\execroot\\_main\\hdl\\chisel\\src\\accel\\npu\\MmaEngine.scala:187:29, :227:19, :303:43, :311:49, :324:{30,49}
        end
        else	// C:\\Users\\admin\\.bazel\\2ryzlsy4\\execroot\\_main\\hdl\\chisel\\src\\accel\\npu\\MmaEngine.scala:187:29, :227:19, :303:43, :311:49, :324:49
          r_mBlockIdx <= r_mBlockIdx + 16'h1;	// C:\\Users\\admin\\.bazel\\2ryzlsy4\\execroot\\_main\\hdl\\chisel\\src\\accel\\npu\\MmaEngine.scala:187:29, :326:36
        if (_GEN_5 | _GEN_4 | _GEN) begin	// C:\\Users\\admin\\.bazel\\2ryzlsy4\\execroot\\_main\\hdl\\chisel\\src\\accel\\npu\\MmaEngine.scala:187:29, :188:29, :227:19, :303:{24,43}
        end
        else if (_GEN_0)	// C:\\Users\\admin\\.bazel\\2ryzlsy4\\execroot\\_main\\hdl\\chisel\\src\\accel\\npu\\MmaEngine.scala:311:30
          r_nBlockIdx <= r_nBlockIdx + 16'h1;	// C:\\Users\\admin\\.bazel\\2ryzlsy4\\execroot\\_main\\hdl\\chisel\\src\\accel\\npu\\MmaEngine.scala:188:29, :313:36
        else if (_GEN_1)	// C:\\Users\\admin\\.bazel\\2ryzlsy4\\execroot\\_main\\hdl\\chisel\\src\\accel\\npu\\MmaEngine.scala:324:30
          r_nBlockIdx <= 16'h0;	// C:\\Users\\admin\\.bazel\\2ryzlsy4\\execroot\\_main\\hdl\\chisel\\src\\accel\\npu\\MmaEngine.scala:188:29
        if (_GEN_5 | _GEN_4) begin	// C:\\Users\\admin\\.bazel\\2ryzlsy4\\execroot\\_main\\hdl\\chisel\\src\\accel\\npu\\MmaEngine.scala:187:29, :189:29, :227:19
        end
        else if (_GEN)	// C:\\Users\\admin\\.bazel\\2ryzlsy4\\execroot\\_main\\hdl\\chisel\\src\\accel\\npu\\MmaEngine.scala:303:24
          r_kBlockIdx <= r_kBlockIdx + 16'h1;	// C:\\Users\\admin\\.bazel\\2ryzlsy4\\execroot\\_main\\hdl\\chisel\\src\\accel\\npu\\MmaEngine.scala:189:29, :304:36
        else if (_GEN_0 | _GEN_1)	// C:\\Users\\admin\\.bazel\\2ryzlsy4\\execroot\\_main\\hdl\\chisel\\src\\accel\\npu\\MmaEngine.scala:189:29, :311:{30,49}, :314:21, :324:{30,49}, :328:21
          r_kBlockIdx <= 16'h0;	// C:\\Users\\admin\\.bazel\\2ryzlsy4\\execroot\\_main\\hdl\\chisel\\src\\accel\\npu\\MmaEngine.scala:189:29
      end
    end
  end // always @(posedge)
  `ifdef ENABLE_INITIAL_REG_	// C:\\Users\\admin\\.bazel\\2ryzlsy4\\execroot\\_main\\hdl\\chisel\\src\\accel\\npu\\MmaEngine.scala:120:7
    `ifdef FIRRTL_BEFORE_INITIAL	// C:\\Users\\admin\\.bazel\\2ryzlsy4\\execroot\\_main\\hdl\\chisel\\src\\accel\\npu\\MmaEngine.scala:120:7
      `FIRRTL_BEFORE_INITIAL	// C:\\Users\\admin\\.bazel\\2ryzlsy4\\execroot\\_main\\hdl\\chisel\\src\\accel\\npu\\MmaEngine.scala:120:7
    `endif // FIRRTL_BEFORE_INITIAL
    initial begin	// C:\\Users\\admin\\.bazel\\2ryzlsy4\\execroot\\_main\\hdl\\chisel\\src\\accel\\npu\\MmaEngine.scala:120:7
      automatic logic [31:0] _RANDOM[0:4];	// C:\\Users\\admin\\.bazel\\2ryzlsy4\\execroot\\_main\\hdl\\chisel\\src\\accel\\npu\\MmaEngine.scala:120:7
      `ifdef INIT_RANDOM_PROLOG_	// C:\\Users\\admin\\.bazel\\2ryzlsy4\\execroot\\_main\\hdl\\chisel\\src\\accel\\npu\\MmaEngine.scala:120:7
        `INIT_RANDOM_PROLOG_	// C:\\Users\\admin\\.bazel\\2ryzlsy4\\execroot\\_main\\hdl\\chisel\\src\\accel\\npu\\MmaEngine.scala:120:7
      `endif // INIT_RANDOM_PROLOG_
      `ifdef RANDOMIZE_REG_INIT	// C:\\Users\\admin\\.bazel\\2ryzlsy4\\execroot\\_main\\hdl\\chisel\\src\\accel\\npu\\MmaEngine.scala:120:7
        for (logic [2:0] i = 3'h0; i < 3'h5; i += 3'h1) begin
          _RANDOM[i] = `RANDOM;	// C:\\Users\\admin\\.bazel\\2ryzlsy4\\execroot\\_main\\hdl\\chisel\\src\\accel\\npu\\MmaEngine.scala:120:7
        end	// C:\\Users\\admin\\.bazel\\2ryzlsy4\\execroot\\_main\\hdl\\chisel\\src\\accel\\npu\\MmaEngine.scala:120:7
        r_state = _RANDOM[3'h0][2:0];	// C:\\Users\\admin\\.bazel\\2ryzlsy4\\execroot\\_main\\hdl\\chisel\\src\\accel\\npu\\MmaEngine.scala:120:7, :183:29
        r_mBlockIdx = {_RANDOM[3'h2][31:24], _RANDOM[3'h3][7:0]};	// C:\\Users\\admin\\.bazel\\2ryzlsy4\\execroot\\_main\\hdl\\chisel\\src\\accel\\npu\\MmaEngine.scala:120:7, :187:29
        r_nBlockIdx = _RANDOM[3'h3][23:8];	// C:\\Users\\admin\\.bazel\\2ryzlsy4\\execroot\\_main\\hdl\\chisel\\src\\accel\\npu\\MmaEngine.scala:120:7, :187:29, :188:29
        r_kBlockIdx = {_RANDOM[3'h3][31:24], _RANDOM[3'h4][7:0]};	// C:\\Users\\admin\\.bazel\\2ryzlsy4\\execroot\\_main\\hdl\\chisel\\src\\accel\\npu\\MmaEngine.scala:120:7, :187:29, :189:29
      `endif // RANDOMIZE_REG_INIT
    end // initial
    `ifdef FIRRTL_AFTER_INITIAL	// C:\\Users\\admin\\.bazel\\2ryzlsy4\\execroot\\_main\\hdl\\chisel\\src\\accel\\npu\\MmaEngine.scala:120:7
      `FIRRTL_AFTER_INITIAL	// C:\\Users\\admin\\.bazel\\2ryzlsy4\\execroot\\_main\\hdl\\chisel\\src\\accel\\npu\\MmaEngine.scala:120:7
    `endif // FIRRTL_AFTER_INITIAL
  `endif // ENABLE_INITIAL_REG_
  assign io_busy = |r_state;	// C:\\Users\\admin\\.bazel\\2ryzlsy4\\execroot\\_main\\hdl\\chisel\\src\\accel\\npu\\MmaEngine.scala:120:7, :183:29, :386:27
  assign io_done = r_state == 3'h5;	// C:\\Users\\admin\\.bazel\\2ryzlsy4\\execroot\\_main\\hdl\\chisel\\src\\accel\\npu\\MmaEngine.scala:120:7, :183:29, :387:27
endmodule

module SoftmaxUnit(	// C:\\Users\\admin\\.bazel\\2ryzlsy4\\execroot\\_main\\hdl\\chisel\\src\\accel\\npu\\AttnEngine.scala:133:7
  input  clock,	// C:\\Users\\admin\\.bazel\\2ryzlsy4\\execroot\\_main\\hdl\\chisel\\src\\accel\\npu\\AttnEngine.scala:133:7
         reset,	// C:\\Users\\admin\\.bazel\\2ryzlsy4\\execroot\\_main\\hdl\\chisel\\src\\accel\\npu\\AttnEngine.scala:133:7
         io_start,	// C:\\Users\\admin\\.bazel\\2ryzlsy4\\execroot\\_main\\hdl\\chisel\\src\\accel\\npu\\AttnEngine.scala:138:14
  output io_done,	// C:\\Users\\admin\\.bazel\\2ryzlsy4\\execroot\\_main\\hdl\\chisel\\src\\accel\\npu\\AttnEngine.scala:138:14
         io_busy	// C:\\Users\\admin\\.bazel\\2ryzlsy4\\execroot\\_main\\hdl\\chisel\\src\\accel\\npu\\AttnEngine.scala:138:14
);

  reg [2:0] r_state;	// C:\\Users\\admin\\.bazel\\2ryzlsy4\\execroot\\_main\\hdl\\chisel\\src\\accel\\npu\\AttnEngine.scala:172:27
  always @(posedge clock) begin	// C:\\Users\\admin\\.bazel\\2ryzlsy4\\execroot\\_main\\hdl\\chisel\\src\\accel\\npu\\AttnEngine.scala:133:7
    if (reset)	// C:\\Users\\admin\\.bazel\\2ryzlsy4\\execroot\\_main\\hdl\\chisel\\src\\accel\\npu\\AttnEngine.scala:133:7
      r_state <= 3'h0;	// C:\\Users\\admin\\.bazel\\2ryzlsy4\\execroot\\_main\\hdl\\chisel\\src\\accel\\npu\\AttnEngine.scala:172:27, :272:15
    else if (r_state == 3'h0) begin	// C:\\Users\\admin\\.bazel\\2ryzlsy4\\execroot\\_main\\hdl\\chisel\\src\\accel\\npu\\AttnEngine.scala:172:27, :196:19, :272:15
      if (io_start)	// C:\\Users\\admin\\.bazel\\2ryzlsy4\\execroot\\_main\\hdl\\chisel\\src\\accel\\npu\\AttnEngine.scala:138:14
        r_state <= 3'h1;	// C:\\Users\\admin\\.bazel\\2ryzlsy4\\execroot\\_main\\hdl\\chisel\\src\\accel\\npu\\AttnEngine.scala:172:27
    end
    else if (r_state == 3'h1 | r_state == 3'h2 | r_state == 3'h3 | r_state != 3'h4) begin	// C:\\Users\\admin\\.bazel\\2ryzlsy4\\execroot\\_main\\hdl\\chisel\\src\\accel\\npu\\AttnEngine.scala:172:27, :196:19, :210:28, :225:28, :248:47, :266:19
    end
    else	// C:\\Users\\admin\\.bazel\\2ryzlsy4\\execroot\\_main\\hdl\\chisel\\src\\accel\\npu\\AttnEngine.scala:196:19, :210:28, :225:28, :248:47
      r_state <= 3'h0;	// C:\\Users\\admin\\.bazel\\2ryzlsy4\\execroot\\_main\\hdl\\chisel\\src\\accel\\npu\\AttnEngine.scala:172:27, :272:15
  end // always @(posedge)
  `ifdef ENABLE_INITIAL_REG_	// C:\\Users\\admin\\.bazel\\2ryzlsy4\\execroot\\_main\\hdl\\chisel\\src\\accel\\npu\\AttnEngine.scala:133:7
    `ifdef FIRRTL_BEFORE_INITIAL	// C:\\Users\\admin\\.bazel\\2ryzlsy4\\execroot\\_main\\hdl\\chisel\\src\\accel\\npu\\AttnEngine.scala:133:7
      `FIRRTL_BEFORE_INITIAL	// C:\\Users\\admin\\.bazel\\2ryzlsy4\\execroot\\_main\\hdl\\chisel\\src\\accel\\npu\\AttnEngine.scala:133:7
    `endif // FIRRTL_BEFORE_INITIAL
    initial begin	// C:\\Users\\admin\\.bazel\\2ryzlsy4\\execroot\\_main\\hdl\\chisel\\src\\accel\\npu\\AttnEngine.scala:133:7
      automatic logic [31:0] _RANDOM[0:0];	// C:\\Users\\admin\\.bazel\\2ryzlsy4\\execroot\\_main\\hdl\\chisel\\src\\accel\\npu\\AttnEngine.scala:133:7
      `ifdef INIT_RANDOM_PROLOG_	// C:\\Users\\admin\\.bazel\\2ryzlsy4\\execroot\\_main\\hdl\\chisel\\src\\accel\\npu\\AttnEngine.scala:133:7
        `INIT_RANDOM_PROLOG_	// C:\\Users\\admin\\.bazel\\2ryzlsy4\\execroot\\_main\\hdl\\chisel\\src\\accel\\npu\\AttnEngine.scala:133:7
      `endif // INIT_RANDOM_PROLOG_
      `ifdef RANDOMIZE_REG_INIT	// C:\\Users\\admin\\.bazel\\2ryzlsy4\\execroot\\_main\\hdl\\chisel\\src\\accel\\npu\\AttnEngine.scala:133:7
        _RANDOM[/*Zero width*/ 1'b0] = `RANDOM;	// C:\\Users\\admin\\.bazel\\2ryzlsy4\\execroot\\_main\\hdl\\chisel\\src\\accel\\npu\\AttnEngine.scala:133:7
        r_state = _RANDOM[/*Zero width*/ 1'b0][2:0];	// C:\\Users\\admin\\.bazel\\2ryzlsy4\\execroot\\_main\\hdl\\chisel\\src\\accel\\npu\\AttnEngine.scala:133:7, :172:27
      `endif // RANDOMIZE_REG_INIT
    end // initial
    `ifdef FIRRTL_AFTER_INITIAL	// C:\\Users\\admin\\.bazel\\2ryzlsy4\\execroot\\_main\\hdl\\chisel\\src\\accel\\npu\\AttnEngine.scala:133:7
      `FIRRTL_AFTER_INITIAL	// C:\\Users\\admin\\.bazel\\2ryzlsy4\\execroot\\_main\\hdl\\chisel\\src\\accel\\npu\\AttnEngine.scala:133:7
    `endif // FIRRTL_AFTER_INITIAL
  `endif // ENABLE_INITIAL_REG_
  assign io_done = r_state == 3'h4;	// C:\\Users\\admin\\.bazel\\2ryzlsy4\\execroot\\_main\\hdl\\chisel\\src\\accel\\npu\\AttnEngine.scala:133:7, :172:27, :266:19, :282:29
  assign io_busy = |r_state;	// C:\\Users\\admin\\.bazel\\2ryzlsy4\\execroot\\_main\\hdl\\chisel\\src\\accel\\npu\\AttnEngine.scala:133:7, :172:27, :281:29
endmodule

module AttnEngine(	// C:\\Users\\admin\\.bazel\\2ryzlsy4\\execroot\\_main\\hdl\\chisel\\src\\accel\\npu\\AttnEngine.scala:328:7
  input  clock,	// C:\\Users\\admin\\.bazel\\2ryzlsy4\\execroot\\_main\\hdl\\chisel\\src\\accel\\npu\\AttnEngine.scala:328:7
         reset,	// C:\\Users\\admin\\.bazel\\2ryzlsy4\\execroot\\_main\\hdl\\chisel\\src\\accel\\npu\\AttnEngine.scala:328:7
  output io_done	// C:\\Users\\admin\\.bazel\\2ryzlsy4\\execroot\\_main\\hdl\\chisel\\src\\accel\\npu\\AttnEngine.scala:329:14
);

  wire       _softmax_io_done;	// C:\\Users\\admin\\.bazel\\2ryzlsy4\\execroot\\_main\\hdl\\chisel\\src\\accel\\npu\\AttnEngine.scala:403:23
  wire       _softmax_io_busy;	// C:\\Users\\admin\\.bazel\\2ryzlsy4\\execroot\\_main\\hdl\\chisel\\src\\accel\\npu\\AttnEngine.scala:403:23
  wire       _mmaAV_io_busy;	// C:\\Users\\admin\\.bazel\\2ryzlsy4\\execroot\\_main\\hdl\\chisel\\src\\accel\\npu\\AttnEngine.scala:398:21
  wire       _mmaAV_io_done;	// C:\\Users\\admin\\.bazel\\2ryzlsy4\\execroot\\_main\\hdl\\chisel\\src\\accel\\npu\\AttnEngine.scala:398:21
  wire       _mmaQK_io_busy;	// C:\\Users\\admin\\.bazel\\2ryzlsy4\\execroot\\_main\\hdl\\chisel\\src\\accel\\npu\\AttnEngine.scala:393:21
  wire       _mmaQK_io_done;	// C:\\Users\\admin\\.bazel\\2ryzlsy4\\execroot\\_main\\hdl\\chisel\\src\\accel\\npu\\AttnEngine.scala:393:21
  reg  [2:0] r_state;	// C:\\Users\\admin\\.bazel\\2ryzlsy4\\execroot\\_main\\hdl\\chisel\\src\\accel\\npu\\AttnEngine.scala:409:27
  reg  [1:0] r_headIdx;	// C:\\Users\\admin\\.bazel\\2ryzlsy4\\execroot\\_main\\hdl\\chisel\\src\\accel\\npu\\AttnEngine.scala:411:27
  wire       _GEN = r_state == 3'h0;	// C:\\Users\\admin\\.bazel\\2ryzlsy4\\execroot\\_main\\hdl\\chisel\\src\\accel\\npu\\AttnEngine.scala:409:27, :425:19, :483:15
  wire       _GEN_0 = r_state == 3'h1;	// C:\\Users\\admin\\.bazel\\2ryzlsy4\\execroot\\_main\\hdl\\chisel\\src\\accel\\npu\\AttnEngine.scala:409:27, :425:19, :437:37
  wire       _GEN_1 = r_state == 3'h2;	// C:\\Users\\admin\\.bazel\\2ryzlsy4\\execroot\\_main\\hdl\\chisel\\src\\accel\\npu\\AttnEngine.scala:409:27, :425:19
  wire       _GEN_2 = r_state == 3'h3;	// C:\\Users\\admin\\.bazel\\2ryzlsy4\\execroot\\_main\\hdl\\chisel\\src\\accel\\npu\\AttnEngine.scala:409:27, :425:19
  wire       _GEN_3 = r_state == 3'h4;	// C:\\Users\\admin\\.bazel\\2ryzlsy4\\execroot\\_main\\hdl\\chisel\\src\\accel\\npu\\AttnEngine.scala:409:27, :425:19, :455:15
  wire       _GEN_4 = r_state == 3'h5;	// C:\\Users\\admin\\.bazel\\2ryzlsy4\\execroot\\_main\\hdl\\chisel\\src\\accel\\npu\\AttnEngine.scala:409:27, :425:19, :462:17
  wire       _GEN_5 = _GEN | _GEN_0 | _GEN_1 | _GEN_2 | _GEN_3;	// C:\\Users\\admin\\.bazel\\2ryzlsy4\\execroot\\_main\\hdl\\chisel\\src\\accel\\npu\\AttnEngine.scala:422:21, :425:19
  always @(posedge clock) begin	// C:\\Users\\admin\\.bazel\\2ryzlsy4\\execroot\\_main\\hdl\\chisel\\src\\accel\\npu\\AttnEngine.scala:328:7
    if (reset) begin	// C:\\Users\\admin\\.bazel\\2ryzlsy4\\execroot\\_main\\hdl\\chisel\\src\\accel\\npu\\AttnEngine.scala:328:7
      r_state <= 3'h0;	// C:\\Users\\admin\\.bazel\\2ryzlsy4\\execroot\\_main\\hdl\\chisel\\src\\accel\\npu\\AttnEngine.scala:409:27, :483:15
      r_headIdx <= 2'h0;	// C:\\Users\\admin\\.bazel\\2ryzlsy4\\execroot\\_main\\hdl\\chisel\\src\\accel\\npu\\AttnEngine.scala:328:7, :411:27
    end
    else begin	// C:\\Users\\admin\\.bazel\\2ryzlsy4\\execroot\\_main\\hdl\\chisel\\src\\accel\\npu\\AttnEngine.scala:328:7
      automatic logic            _GEN_6;	// C:\\Users\\admin\\.bazel\\2ryzlsy4\\execroot\\_main\\hdl\\chisel\\src\\accel\\npu\\AttnEngine.scala:471:24
      automatic logic [7:0][2:0] _GEN_7;	// C:\\Users\\admin\\.bazel\\2ryzlsy4\\execroot\\_main\\hdl\\chisel\\src\\accel\\npu\\AttnEngine.scala:409:27, :425:19, :427:25, :438:27, :446:15, :455:15, :461:29, :469:27, :483:15
      _GEN_6 = r_headIdx != 2'h3;	// C:\\Users\\admin\\.bazel\\2ryzlsy4\\execroot\\_main\\hdl\\chisel\\src\\accel\\npu\\AttnEngine.scala:328:7, :411:27, :471:24
      _GEN_7 =
        {{r_state},
         {3'h0},
         {_mmaAV_io_done ? (_GEN_6 ? 3'h1 : 3'h6) : r_state},
         {_softmax_io_done ? 3'h5 : r_state},
         {3'h4},
         {3'h3},
         {_mmaQK_io_done ? 3'h2 : r_state},
         {r_state}};	// C:\\Users\\admin\\.bazel\\2ryzlsy4\\execroot\\_main\\hdl\\chisel\\src\\accel\\npu\\AttnEngine.scala:393:21, :398:21, :403:23, :409:27, :425:19, :427:25, :437:37, :438:27, :439:17, :446:15, :455:15, :461:29, :462:17, :469:27, :471:{24,48}, :473:21, :476:19, :483:15
      r_state <= _GEN_7[r_state];	// C:\\Users\\admin\\.bazel\\2ryzlsy4\\execroot\\_main\\hdl\\chisel\\src\\accel\\npu\\AttnEngine.scala:409:27, :425:19, :427:25, :438:27, :446:15, :455:15, :461:29, :469:27, :483:15
      if (_GEN_5 | ~(_GEN_4 & _mmaAV_io_done & _GEN_6)) begin	// C:\\Users\\admin\\.bazel\\2ryzlsy4\\execroot\\_main\\hdl\\chisel\\src\\accel\\npu\\AttnEngine.scala:398:21, :411:27, :422:21, :425:19, :427:25, :469:27, :471:{24,48}, :472:21
      end
      else	// C:\\Users\\admin\\.bazel\\2ryzlsy4\\execroot\\_main\\hdl\\chisel\\src\\accel\\npu\\AttnEngine.scala:411:27, :425:19, :427:25
        r_headIdx <= r_headIdx + 2'h1;	// C:\\Users\\admin\\.bazel\\2ryzlsy4\\execroot\\_main\\hdl\\chisel\\src\\accel\\npu\\AttnEngine.scala:328:7, :411:27, :472:34
    end
  end // always @(posedge)
  `ifdef ENABLE_INITIAL_REG_	// C:\\Users\\admin\\.bazel\\2ryzlsy4\\execroot\\_main\\hdl\\chisel\\src\\accel\\npu\\AttnEngine.scala:328:7
    `ifdef FIRRTL_BEFORE_INITIAL	// C:\\Users\\admin\\.bazel\\2ryzlsy4\\execroot\\_main\\hdl\\chisel\\src\\accel\\npu\\AttnEngine.scala:328:7
      `FIRRTL_BEFORE_INITIAL	// C:\\Users\\admin\\.bazel\\2ryzlsy4\\execroot\\_main\\hdl\\chisel\\src\\accel\\npu\\AttnEngine.scala:328:7
    `endif // FIRRTL_BEFORE_INITIAL
    initial begin	// C:\\Users\\admin\\.bazel\\2ryzlsy4\\execroot\\_main\\hdl\\chisel\\src\\accel\\npu\\AttnEngine.scala:328:7
      automatic logic [31:0] _RANDOM[0:2];	// C:\\Users\\admin\\.bazel\\2ryzlsy4\\execroot\\_main\\hdl\\chisel\\src\\accel\\npu\\AttnEngine.scala:328:7
      `ifdef INIT_RANDOM_PROLOG_	// C:\\Users\\admin\\.bazel\\2ryzlsy4\\execroot\\_main\\hdl\\chisel\\src\\accel\\npu\\AttnEngine.scala:328:7
        `INIT_RANDOM_PROLOG_	// C:\\Users\\admin\\.bazel\\2ryzlsy4\\execroot\\_main\\hdl\\chisel\\src\\accel\\npu\\AttnEngine.scala:328:7
      `endif // INIT_RANDOM_PROLOG_
      `ifdef RANDOMIZE_REG_INIT	// C:\\Users\\admin\\.bazel\\2ryzlsy4\\execroot\\_main\\hdl\\chisel\\src\\accel\\npu\\AttnEngine.scala:328:7
        for (logic [1:0] i = 2'h0; i < 2'h3; i += 2'h1) begin
          _RANDOM[i] = `RANDOM;	// C:\\Users\\admin\\.bazel\\2ryzlsy4\\execroot\\_main\\hdl\\chisel\\src\\accel\\npu\\AttnEngine.scala:328:7
        end	// C:\\Users\\admin\\.bazel\\2ryzlsy4\\execroot\\_main\\hdl\\chisel\\src\\accel\\npu\\AttnEngine.scala:328:7
        r_state = _RANDOM[2'h0][2:0];	// C:\\Users\\admin\\.bazel\\2ryzlsy4\\execroot\\_main\\hdl\\chisel\\src\\accel\\npu\\AttnEngine.scala:328:7, :409:27
        r_headIdx = _RANDOM[2'h2][17:16];	// C:\\Users\\admin\\.bazel\\2ryzlsy4\\execroot\\_main\\hdl\\chisel\\src\\accel\\npu\\AttnEngine.scala:328:7, :411:27
      `endif // RANDOMIZE_REG_INIT
    end // initial
    `ifdef FIRRTL_AFTER_INITIAL	// C:\\Users\\admin\\.bazel\\2ryzlsy4\\execroot\\_main\\hdl\\chisel\\src\\accel\\npu\\AttnEngine.scala:328:7
      `FIRRTL_AFTER_INITIAL	// C:\\Users\\admin\\.bazel\\2ryzlsy4\\execroot\\_main\\hdl\\chisel\\src\\accel\\npu\\AttnEngine.scala:328:7
    `endif // FIRRTL_AFTER_INITIAL
  `endif // ENABLE_INITIAL_REG_
  MmaEngine mmaQK (	// C:\\Users\\admin\\.bazel\\2ryzlsy4\\execroot\\_main\\hdl\\chisel\\src\\accel\\npu\\AttnEngine.scala:393:21
    .clock          (clock),
    .reset          (reset),
    .io_cmdValid    (~_GEN & _GEN_0 & r_state == 3'h1 & ~_mmaQK_io_busy),	// C:\\Users\\admin\\.bazel\\2ryzlsy4\\execroot\\_main\\hdl\\chisel\\src\\accel\\npu\\AttnEngine.scala:393:21, :409:27, :421:21, :425:19, :437:{25,37,60,63}
    .io_cWriteReady (1'h1),
    .io_busy        (_mmaQK_io_busy),
    .io_done        (_mmaQK_io_done)
  );	// C:\\Users\\admin\\.bazel\\2ryzlsy4\\execroot\\_main\\hdl\\chisel\\src\\accel\\npu\\AttnEngine.scala:393:21
  MmaEngine mmaAV (	// C:\\Users\\admin\\.bazel\\2ryzlsy4\\execroot\\_main\\hdl\\chisel\\src\\accel\\npu\\AttnEngine.scala:398:21
    .clock          (clock),
    .reset          (reset),
    .io_cmdValid    (~_GEN_5 & _GEN_4 & r_state == 3'h5 & ~_mmaAV_io_busy),	// C:\\Users\\admin\\.bazel\\2ryzlsy4\\execroot\\_main\\hdl\\chisel\\src\\accel\\npu\\AttnEngine.scala:398:21, :409:27, :422:21, :425:19, :462:17, :468:{25,37,60,63}
    .io_cWriteReady (1'h1),
    .io_busy        (_mmaAV_io_busy),
    .io_done        (_mmaAV_io_done)
  );	// C:\\Users\\admin\\.bazel\\2ryzlsy4\\execroot\\_main\\hdl\\chisel\\src\\accel\\npu\\AttnEngine.scala:398:21
  SoftmaxUnit softmax (	// C:\\Users\\admin\\.bazel\\2ryzlsy4\\execroot\\_main\\hdl\\chisel\\src\\accel\\npu\\AttnEngine.scala:403:23
    .clock    (clock),
    .reset    (reset),
    .io_start
      (~(_GEN | _GEN_0 | _GEN_1 | _GEN_2) & _GEN_3 & r_state == 3'h4 & ~_softmax_io_busy),	// C:\\Users\\admin\\.bazel\\2ryzlsy4\\execroot\\_main\\hdl\\chisel\\src\\accel\\npu\\AttnEngine.scala:403:23, :409:27, :423:21, :425:19, :455:15, :460:{24,36,64,67}
    .io_done  (_softmax_io_done),
    .io_busy  (_softmax_io_busy)
  );	// C:\\Users\\admin\\.bazel\\2ryzlsy4\\execroot\\_main\\hdl\\chisel\\src\\accel\\npu\\AttnEngine.scala:403:23
  assign io_done = r_state == 3'h6;	// C:\\Users\\admin\\.bazel\\2ryzlsy4\\execroot\\_main\\hdl\\chisel\\src\\accel\\npu\\AttnEngine.scala:328:7, :409:27, :476:19, :533:30
endmodule

module NpuTop(	// C:\\Users\\admin\\.bazel\\2ryzlsy4\\execroot\\_main\\hdl\\chisel\\src\\accel\\npu\\NpuTop.scala:47:7
  input         clock,	// C:\\Users\\admin\\.bazel\\2ryzlsy4\\execroot\\_main\\hdl\\chisel\\src\\accel\\npu\\NpuTop.scala:47:7
                reset,	// C:\\Users\\admin\\.bazel\\2ryzlsy4\\execroot\\_main\\hdl\\chisel\\src\\accel\\npu\\NpuTop.scala:47:7
  output        io_cmd_ready,	// C:\\Users\\admin\\.bazel\\2ryzlsy4\\execroot\\_main\\hdl\\chisel\\src\\accel\\npu\\NpuTop.scala:48:14
  input         io_cmd_valid,	// C:\\Users\\admin\\.bazel\\2ryzlsy4\\execroot\\_main\\hdl\\chisel\\src\\accel\\npu\\NpuTop.scala:48:14
                io_cmd_bits_valid,	// C:\\Users\\admin\\.bazel\\2ryzlsy4\\execroot\\_main\\hdl\\chisel\\src\\accel\\npu\\NpuTop.scala:48:14
  input  [2:0]  io_cmd_bits_opcode,	// C:\\Users\\admin\\.bazel\\2ryzlsy4\\execroot\\_main\\hdl\\chisel\\src\\accel\\npu\\NpuTop.scala:48:14
  input  [63:0] io_cmd_bits_srcAddr,	// C:\\Users\\admin\\.bazel\\2ryzlsy4\\execroot\\_main\\hdl\\chisel\\src\\accel\\npu\\NpuTop.scala:48:14
                io_cmd_bits_dstAddr,	// C:\\Users\\admin\\.bazel\\2ryzlsy4\\execroot\\_main\\hdl\\chisel\\src\\accel\\npu\\NpuTop.scala:48:14
  input  [15:0] io_cmd_bits_dimM,	// C:\\Users\\admin\\.bazel\\2ryzlsy4\\execroot\\_main\\hdl\\chisel\\src\\accel\\npu\\NpuTop.scala:48:14
                io_cmd_bits_dimN,	// C:\\Users\\admin\\.bazel\\2ryzlsy4\\execroot\\_main\\hdl\\chisel\\src\\accel\\npu\\NpuTop.scala:48:14
                io_cmd_bits_dimK,	// C:\\Users\\admin\\.bazel\\2ryzlsy4\\execroot\\_main\\hdl\\chisel\\src\\accel\\npu\\NpuTop.scala:48:14
  input  [7:0]  io_cmd_bits_cmdId,	// C:\\Users\\admin\\.bazel\\2ryzlsy4\\execroot\\_main\\hdl\\chisel\\src\\accel\\npu\\NpuTop.scala:48:14
  output        io_completion_valid,	// C:\\Users\\admin\\.bazel\\2ryzlsy4\\execroot\\_main\\hdl\\chisel\\src\\accel\\npu\\NpuTop.scala:48:14
                io_completion_error,	// C:\\Users\\admin\\.bazel\\2ryzlsy4\\execroot\\_main\\hdl\\chisel\\src\\accel\\npu\\NpuTop.scala:48:14
  output [7:0]  io_completion_errCode,	// C:\\Users\\admin\\.bazel\\2ryzlsy4\\execroot\\_main\\hdl\\chisel\\src\\accel\\npu\\NpuTop.scala:48:14
  output [63:0] io_axiMaster_aw_addr,	// C:\\Users\\admin\\.bazel\\2ryzlsy4\\execroot\\_main\\hdl\\chisel\\src\\accel\\npu\\NpuTop.scala:48:14
  output [3:0]  io_axiMaster_aw_id,	// C:\\Users\\admin\\.bazel\\2ryzlsy4\\execroot\\_main\\hdl\\chisel\\src\\accel\\npu\\NpuTop.scala:48:14
  output [7:0]  io_axiMaster_aw_len,	// C:\\Users\\admin\\.bazel\\2ryzlsy4\\execroot\\_main\\hdl\\chisel\\src\\accel\\npu\\NpuTop.scala:48:14
  output [2:0]  io_axiMaster_aw_size,	// C:\\Users\\admin\\.bazel\\2ryzlsy4\\execroot\\_main\\hdl\\chisel\\src\\accel\\npu\\NpuTop.scala:48:14
  output [1:0]  io_axiMaster_aw_burst,	// C:\\Users\\admin\\.bazel\\2ryzlsy4\\execroot\\_main\\hdl\\chisel\\src\\accel\\npu\\NpuTop.scala:48:14
  output        io_axiMaster_aw_lock,	// C:\\Users\\admin\\.bazel\\2ryzlsy4\\execroot\\_main\\hdl\\chisel\\src\\accel\\npu\\NpuTop.scala:48:14
  output [3:0]  io_axiMaster_aw_cache,	// C:\\Users\\admin\\.bazel\\2ryzlsy4\\execroot\\_main\\hdl\\chisel\\src\\accel\\npu\\NpuTop.scala:48:14
  output [2:0]  io_axiMaster_aw_prot,	// C:\\Users\\admin\\.bazel\\2ryzlsy4\\execroot\\_main\\hdl\\chisel\\src\\accel\\npu\\NpuTop.scala:48:14
  output [3:0]  io_axiMaster_aw_qos,	// C:\\Users\\admin\\.bazel\\2ryzlsy4\\execroot\\_main\\hdl\\chisel\\src\\accel\\npu\\NpuTop.scala:48:14
                io_axiMaster_aw_region,	// C:\\Users\\admin\\.bazel\\2ryzlsy4\\execroot\\_main\\hdl\\chisel\\src\\accel\\npu\\NpuTop.scala:48:14
  output        io_axiMaster_aw_user,	// C:\\Users\\admin\\.bazel\\2ryzlsy4\\execroot\\_main\\hdl\\chisel\\src\\accel\\npu\\NpuTop.scala:48:14
                io_axiMaster_aw_valid,	// C:\\Users\\admin\\.bazel\\2ryzlsy4\\execroot\\_main\\hdl\\chisel\\src\\accel\\npu\\NpuTop.scala:48:14
  input         io_axiMaster_aw_ready,	// C:\\Users\\admin\\.bazel\\2ryzlsy4\\execroot\\_main\\hdl\\chisel\\src\\accel\\npu\\NpuTop.scala:48:14
  output [31:0] io_axiMaster_w_data,	// C:\\Users\\admin\\.bazel\\2ryzlsy4\\execroot\\_main\\hdl\\chisel\\src\\accel\\npu\\NpuTop.scala:48:14
  output [3:0]  io_axiMaster_w_strb,	// C:\\Users\\admin\\.bazel\\2ryzlsy4\\execroot\\_main\\hdl\\chisel\\src\\accel\\npu\\NpuTop.scala:48:14
  output        io_axiMaster_w_last,	// C:\\Users\\admin\\.bazel\\2ryzlsy4\\execroot\\_main\\hdl\\chisel\\src\\accel\\npu\\NpuTop.scala:48:14
                io_axiMaster_w_user,	// C:\\Users\\admin\\.bazel\\2ryzlsy4\\execroot\\_main\\hdl\\chisel\\src\\accel\\npu\\NpuTop.scala:48:14
                io_axiMaster_w_valid,	// C:\\Users\\admin\\.bazel\\2ryzlsy4\\execroot\\_main\\hdl\\chisel\\src\\accel\\npu\\NpuTop.scala:48:14
  input         io_axiMaster_w_ready,	// C:\\Users\\admin\\.bazel\\2ryzlsy4\\execroot\\_main\\hdl\\chisel\\src\\accel\\npu\\NpuTop.scala:48:14
  input  [3:0]  io_axiMaster_b_id,	// C:\\Users\\admin\\.bazel\\2ryzlsy4\\execroot\\_main\\hdl\\chisel\\src\\accel\\npu\\NpuTop.scala:48:14
  input  [1:0]  io_axiMaster_b_resp,	// C:\\Users\\admin\\.bazel\\2ryzlsy4\\execroot\\_main\\hdl\\chisel\\src\\accel\\npu\\NpuTop.scala:48:14
  input         io_axiMaster_b_user,	// C:\\Users\\admin\\.bazel\\2ryzlsy4\\execroot\\_main\\hdl\\chisel\\src\\accel\\npu\\NpuTop.scala:48:14
                io_axiMaster_b_valid,	// C:\\Users\\admin\\.bazel\\2ryzlsy4\\execroot\\_main\\hdl\\chisel\\src\\accel\\npu\\NpuTop.scala:48:14
  output        io_axiMaster_b_ready,	// C:\\Users\\admin\\.bazel\\2ryzlsy4\\execroot\\_main\\hdl\\chisel\\src\\accel\\npu\\NpuTop.scala:48:14
  output [63:0] io_axiMaster_ar_addr,	// C:\\Users\\admin\\.bazel\\2ryzlsy4\\execroot\\_main\\hdl\\chisel\\src\\accel\\npu\\NpuTop.scala:48:14
  output [3:0]  io_axiMaster_ar_id,	// C:\\Users\\admin\\.bazel\\2ryzlsy4\\execroot\\_main\\hdl\\chisel\\src\\accel\\npu\\NpuTop.scala:48:14
  output [7:0]  io_axiMaster_ar_len,	// C:\\Users\\admin\\.bazel\\2ryzlsy4\\execroot\\_main\\hdl\\chisel\\src\\accel\\npu\\NpuTop.scala:48:14
  output [2:0]  io_axiMaster_ar_size,	// C:\\Users\\admin\\.bazel\\2ryzlsy4\\execroot\\_main\\hdl\\chisel\\src\\accel\\npu\\NpuTop.scala:48:14
  output [1:0]  io_axiMaster_ar_burst,	// C:\\Users\\admin\\.bazel\\2ryzlsy4\\execroot\\_main\\hdl\\chisel\\src\\accel\\npu\\NpuTop.scala:48:14
  output        io_axiMaster_ar_lock,	// C:\\Users\\admin\\.bazel\\2ryzlsy4\\execroot\\_main\\hdl\\chisel\\src\\accel\\npu\\NpuTop.scala:48:14
  output [3:0]  io_axiMaster_ar_cache,	// C:\\Users\\admin\\.bazel\\2ryzlsy4\\execroot\\_main\\hdl\\chisel\\src\\accel\\npu\\NpuTop.scala:48:14
  output [2:0]  io_axiMaster_ar_prot,	// C:\\Users\\admin\\.bazel\\2ryzlsy4\\execroot\\_main\\hdl\\chisel\\src\\accel\\npu\\NpuTop.scala:48:14
  output [3:0]  io_axiMaster_ar_qos,	// C:\\Users\\admin\\.bazel\\2ryzlsy4\\execroot\\_main\\hdl\\chisel\\src\\accel\\npu\\NpuTop.scala:48:14
                io_axiMaster_ar_region,	// C:\\Users\\admin\\.bazel\\2ryzlsy4\\execroot\\_main\\hdl\\chisel\\src\\accel\\npu\\NpuTop.scala:48:14
  output        io_axiMaster_ar_user,	// C:\\Users\\admin\\.bazel\\2ryzlsy4\\execroot\\_main\\hdl\\chisel\\src\\accel\\npu\\NpuTop.scala:48:14
                io_axiMaster_ar_valid,	// C:\\Users\\admin\\.bazel\\2ryzlsy4\\execroot\\_main\\hdl\\chisel\\src\\accel\\npu\\NpuTop.scala:48:14
  input         io_axiMaster_ar_ready,	// C:\\Users\\admin\\.bazel\\2ryzlsy4\\execroot\\_main\\hdl\\chisel\\src\\accel\\npu\\NpuTop.scala:48:14
  input  [3:0]  io_axiMaster_r_id,	// C:\\Users\\admin\\.bazel\\2ryzlsy4\\execroot\\_main\\hdl\\chisel\\src\\accel\\npu\\NpuTop.scala:48:14
  input  [31:0] io_axiMaster_r_data,	// C:\\Users\\admin\\.bazel\\2ryzlsy4\\execroot\\_main\\hdl\\chisel\\src\\accel\\npu\\NpuTop.scala:48:14
  input  [1:0]  io_axiMaster_r_resp,	// C:\\Users\\admin\\.bazel\\2ryzlsy4\\execroot\\_main\\hdl\\chisel\\src\\accel\\npu\\NpuTop.scala:48:14
  input         io_axiMaster_r_last,	// C:\\Users\\admin\\.bazel\\2ryzlsy4\\execroot\\_main\\hdl\\chisel\\src\\accel\\npu\\NpuTop.scala:48:14
                io_axiMaster_r_user,	// C:\\Users\\admin\\.bazel\\2ryzlsy4\\execroot\\_main\\hdl\\chisel\\src\\accel\\npu\\NpuTop.scala:48:14
                io_axiMaster_r_valid,	// C:\\Users\\admin\\.bazel\\2ryzlsy4\\execroot\\_main\\hdl\\chisel\\src\\accel\\npu\\NpuTop.scala:48:14
  output        io_axiMaster_r_ready,	// C:\\Users\\admin\\.bazel\\2ryzlsy4\\execroot\\_main\\hdl\\chisel\\src\\accel\\npu\\NpuTop.scala:48:14
  output [31:0] io_perfMatMulCount,	// C:\\Users\\admin\\.bazel\\2ryzlsy4\\execroot\\_main\\hdl\\chisel\\src\\accel\\npu\\NpuTop.scala:48:14
                io_perfConvCount,	// C:\\Users\\admin\\.bazel\\2ryzlsy4\\execroot\\_main\\hdl\\chisel\\src\\accel\\npu\\NpuTop.scala:48:14
                io_perfAttnCount,	// C:\\Users\\admin\\.bazel\\2ryzlsy4\\execroot\\_main\\hdl\\chisel\\src\\accel\\npu\\NpuTop.scala:48:14
                io_perfSparseCount	// C:\\Users\\admin\\.bazel\\2ryzlsy4\\execroot\\_main\\hdl\\chisel\\src\\accel\\npu\\NpuTop.scala:48:14
);

  wire        _u_attnEngine_io_done;	// C:\\Users\\admin\\.bazel\\2ryzlsy4\\execroot\\_main\\hdl\\chisel\\src\\accel\\npu\\NpuTop.scala:100:28
  wire        _u_dmaEngine_io_dmaReq_ready;	// C:\\Users\\admin\\.bazel\\2ryzlsy4\\execroot\\_main\\hdl\\chisel\\src\\accel\\npu\\NpuTop.scala:74:27
  wire        _u_dmaEngine_io_dmaResp_valid;	// C:\\Users\\admin\\.bazel\\2ryzlsy4\\execroot\\_main\\hdl\\chisel\\src\\accel\\npu\\NpuTop.scala:74:27
  wire        _u_npuCore_io_cmd_ready;	// C:\\Users\\admin\\.bazel\\2ryzlsy4\\execroot\\_main\\hdl\\chisel\\src\\accel\\npu\\NpuTop.scala:71:25
  wire        _u_npuCore_io_dmaReq_valid;	// C:\\Users\\admin\\.bazel\\2ryzlsy4\\execroot\\_main\\hdl\\chisel\\src\\accel\\npu\\NpuTop.scala:71:25
  wire [63:0] _u_npuCore_io_dmaReq_bits_addr;	// C:\\Users\\admin\\.bazel\\2ryzlsy4\\execroot\\_main\\hdl\\chisel\\src\\accel\\npu\\NpuTop.scala:71:25
  wire [15:0] _u_npuCore_io_dmaReq_bits_len;	// C:\\Users\\admin\\.bazel\\2ryzlsy4\\execroot\\_main\\hdl\\chisel\\src\\accel\\npu\\NpuTop.scala:71:25
  wire        _u_npuCore_io_dmaReq_bits_isLoad;	// C:\\Users\\admin\\.bazel\\2ryzlsy4\\execroot\\_main\\hdl\\chisel\\src\\accel\\npu\\NpuTop.scala:71:25
  reg  [31:0] r_matmulCount;	// C:\\Users\\admin\\.bazel\\2ryzlsy4\\execroot\\_main\\hdl\\chisel\\src\\accel\\npu\\NpuTop.scala:193:30
  reg  [31:0] r_convCount;	// C:\\Users\\admin\\.bazel\\2ryzlsy4\\execroot\\_main\\hdl\\chisel\\src\\accel\\npu\\NpuTop.scala:194:30
  reg  [31:0] r_attnCount;	// C:\\Users\\admin\\.bazel\\2ryzlsy4\\execroot\\_main\\hdl\\chisel\\src\\accel\\npu\\NpuTop.scala:195:30
  always @(posedge clock) begin	// C:\\Users\\admin\\.bazel\\2ryzlsy4\\execroot\\_main\\hdl\\chisel\\src\\accel\\npu\\NpuTop.scala:47:7
    if (reset) begin	// C:\\Users\\admin\\.bazel\\2ryzlsy4\\execroot\\_main\\hdl\\chisel\\src\\accel\\npu\\NpuTop.scala:47:7
      r_matmulCount <= 32'h0;	// C:\\Users\\admin\\.bazel\\2ryzlsy4\\execroot\\_main\\hdl\\chisel\\src\\accel\\npu\\NpuTop.scala:193:30
      r_convCount <= 32'h0;	// C:\\Users\\admin\\.bazel\\2ryzlsy4\\execroot\\_main\\hdl\\chisel\\src\\accel\\npu\\NpuTop.scala:194:30
      r_attnCount <= 32'h0;	// C:\\Users\\admin\\.bazel\\2ryzlsy4\\execroot\\_main\\hdl\\chisel\\src\\accel\\npu\\NpuTop.scala:195:30
    end
    else begin	// C:\\Users\\admin\\.bazel\\2ryzlsy4\\execroot\\_main\\hdl\\chisel\\src\\accel\\npu\\NpuTop.scala:47:7
      automatic logic _GEN = _u_npuCore_io_cmd_ready & io_cmd_valid;	// C:\\Users\\admin\\.bazel\\2ryzlsy4\\execroot\\_main\\hdl\\chisel\\src\\accel\\npu\\NpuTop.scala:71:25, src/main/scala/chisel3/util/ReadyValidIO.scala:48:35
      if (_GEN & io_cmd_bits_opcode == 3'h1)	// C:\\Users\\admin\\.bazel\\2ryzlsy4\\execroot\\_main\\hdl\\chisel\\src\\accel\\npu\\NpuTop.scala:198:{20,42}, src/main/scala/chisel3/util/ReadyValidIO.scala:48:35
        r_matmulCount <= r_matmulCount + 32'h1;	// C:\\Users\\admin\\.bazel\\2ryzlsy4\\execroot\\_main\\hdl\\chisel\\src\\accel\\npu\\NpuTop.scala:193:30, :199:36
      if (_GEN & io_cmd_bits_opcode == 3'h2)	// C:\\Users\\admin\\.bazel\\2ryzlsy4\\execroot\\_main\\hdl\\chisel\\src\\accel\\npu\\NpuTop.scala:47:7, :74:27, :201:{20,42}, src/main/scala/chisel3/util/ReadyValidIO.scala:48:35
        r_convCount <= r_convCount + 32'h1;	// C:\\Users\\admin\\.bazel\\2ryzlsy4\\execroot\\_main\\hdl\\chisel\\src\\accel\\npu\\NpuTop.scala:194:30, :202:32
      if (_u_attnEngine_io_done)	// C:\\Users\\admin\\.bazel\\2ryzlsy4\\execroot\\_main\\hdl\\chisel\\src\\accel\\npu\\NpuTop.scala:100:28
        r_attnCount <= r_attnCount + 32'h1;	// C:\\Users\\admin\\.bazel\\2ryzlsy4\\execroot\\_main\\hdl\\chisel\\src\\accel\\npu\\NpuTop.scala:195:30, :205:32
    end
  end // always @(posedge)
  `ifdef ENABLE_INITIAL_REG_	// C:\\Users\\admin\\.bazel\\2ryzlsy4\\execroot\\_main\\hdl\\chisel\\src\\accel\\npu\\NpuTop.scala:47:7
    `ifdef FIRRTL_BEFORE_INITIAL	// C:\\Users\\admin\\.bazel\\2ryzlsy4\\execroot\\_main\\hdl\\chisel\\src\\accel\\npu\\NpuTop.scala:47:7
      `FIRRTL_BEFORE_INITIAL	// C:\\Users\\admin\\.bazel\\2ryzlsy4\\execroot\\_main\\hdl\\chisel\\src\\accel\\npu\\NpuTop.scala:47:7
    `endif // FIRRTL_BEFORE_INITIAL
    initial begin	// C:\\Users\\admin\\.bazel\\2ryzlsy4\\execroot\\_main\\hdl\\chisel\\src\\accel\\npu\\NpuTop.scala:47:7
      automatic logic [31:0] _RANDOM[0:2];	// C:\\Users\\admin\\.bazel\\2ryzlsy4\\execroot\\_main\\hdl\\chisel\\src\\accel\\npu\\NpuTop.scala:47:7
      `ifdef INIT_RANDOM_PROLOG_	// C:\\Users\\admin\\.bazel\\2ryzlsy4\\execroot\\_main\\hdl\\chisel\\src\\accel\\npu\\NpuTop.scala:47:7
        `INIT_RANDOM_PROLOG_	// C:\\Users\\admin\\.bazel\\2ryzlsy4\\execroot\\_main\\hdl\\chisel\\src\\accel\\npu\\NpuTop.scala:47:7
      `endif // INIT_RANDOM_PROLOG_
      `ifdef RANDOMIZE_REG_INIT	// C:\\Users\\admin\\.bazel\\2ryzlsy4\\execroot\\_main\\hdl\\chisel\\src\\accel\\npu\\NpuTop.scala:47:7
        for (logic [1:0] i = 2'h0; i < 2'h3; i += 2'h1) begin
          _RANDOM[i] = `RANDOM;	// C:\\Users\\admin\\.bazel\\2ryzlsy4\\execroot\\_main\\hdl\\chisel\\src\\accel\\npu\\NpuTop.scala:47:7
        end	// C:\\Users\\admin\\.bazel\\2ryzlsy4\\execroot\\_main\\hdl\\chisel\\src\\accel\\npu\\NpuTop.scala:47:7
        r_matmulCount = _RANDOM[2'h0];	// C:\\Users\\admin\\.bazel\\2ryzlsy4\\execroot\\_main\\hdl\\chisel\\src\\accel\\npu\\NpuTop.scala:47:7, :193:30
        r_convCount = _RANDOM[2'h1];	// C:\\Users\\admin\\.bazel\\2ryzlsy4\\execroot\\_main\\hdl\\chisel\\src\\accel\\npu\\NpuTop.scala:47:7, :194:30
        r_attnCount = _RANDOM[2'h2];	// C:\\Users\\admin\\.bazel\\2ryzlsy4\\execroot\\_main\\hdl\\chisel\\src\\accel\\npu\\NpuTop.scala:47:7, :195:30
      `endif // RANDOMIZE_REG_INIT
    end // initial
    `ifdef FIRRTL_AFTER_INITIAL	// C:\\Users\\admin\\.bazel\\2ryzlsy4\\execroot\\_main\\hdl\\chisel\\src\\accel\\npu\\NpuTop.scala:47:7
      `FIRRTL_AFTER_INITIAL	// C:\\Users\\admin\\.bazel\\2ryzlsy4\\execroot\\_main\\hdl\\chisel\\src\\accel\\npu\\NpuTop.scala:47:7
    `endif // FIRRTL_AFTER_INITIAL
  `endif // ENABLE_INITIAL_REG_
  NpuCore u_npuCore (	// C:\\Users\\admin\\.bazel\\2ryzlsy4\\execroot\\_main\\hdl\\chisel\\src\\accel\\npu\\NpuTop.scala:71:25
    .clock                 (clock),
    .reset                 (reset),
    .io_cmd_ready          (_u_npuCore_io_cmd_ready),
    .io_cmd_valid          (io_cmd_valid),
    .io_cmd_bits_opcode    (io_cmd_bits_opcode),
    .io_cmd_bits_srcAddr   (io_cmd_bits_srcAddr),
    .io_cmd_bits_dstAddr   (io_cmd_bits_dstAddr),
    .io_cmd_bits_dimM      (io_cmd_bits_dimM),
    .io_cmd_bits_dimN      (io_cmd_bits_dimN),
    .io_cmd_bits_dimK      (io_cmd_bits_dimK),
    .io_status_done        (io_completion_valid),
    .io_status_error       (io_completion_error),
    .io_dmaReq_ready       (_u_dmaEngine_io_dmaReq_ready),	// C:\\Users\\admin\\.bazel\\2ryzlsy4\\execroot\\_main\\hdl\\chisel\\src\\accel\\npu\\NpuTop.scala:74:27
    .io_dmaReq_valid       (_u_npuCore_io_dmaReq_valid),
    .io_dmaReq_bits_addr   (_u_npuCore_io_dmaReq_bits_addr),
    .io_dmaReq_bits_len    (_u_npuCore_io_dmaReq_bits_len),
    .io_dmaReq_bits_isLoad (_u_npuCore_io_dmaReq_bits_isLoad),
    .io_dmaResp_valid      (_u_dmaEngine_io_dmaResp_valid)	// C:\\Users\\admin\\.bazel\\2ryzlsy4\\execroot\\_main\\hdl\\chisel\\src\\accel\\npu\\NpuTop.scala:74:27
  );	// C:\\Users\\admin\\.bazel\\2ryzlsy4\\execroot\\_main\\hdl\\chisel\\src\\accel\\npu\\NpuTop.scala:71:25
  DmaEngine u_dmaEngine (	// C:\\Users\\admin\\.bazel\\2ryzlsy4\\execroot\\_main\\hdl\\chisel\\src\\accel\\npu\\NpuTop.scala:74:27
    .clock                 (clock),
    .reset                 (reset),
    .io_dmaReq_ready       (_u_dmaEngine_io_dmaReq_ready),
    .io_dmaReq_valid       (_u_npuCore_io_dmaReq_valid),	// C:\\Users\\admin\\.bazel\\2ryzlsy4\\execroot\\_main\\hdl\\chisel\\src\\accel\\npu\\NpuTop.scala:71:25
    .io_dmaReq_bits_addr   (_u_npuCore_io_dmaReq_bits_addr),	// C:\\Users\\admin\\.bazel\\2ryzlsy4\\execroot\\_main\\hdl\\chisel\\src\\accel\\npu\\NpuTop.scala:71:25
    .io_dmaReq_bits_len    (_u_npuCore_io_dmaReq_bits_len),	// C:\\Users\\admin\\.bazel\\2ryzlsy4\\execroot\\_main\\hdl\\chisel\\src\\accel\\npu\\NpuTop.scala:71:25
    .io_dmaReq_bits_isLoad (_u_npuCore_io_dmaReq_bits_isLoad),	// C:\\Users\\admin\\.bazel\\2ryzlsy4\\execroot\\_main\\hdl\\chisel\\src\\accel\\npu\\NpuTop.scala:71:25
    .io_dmaResp_valid      (_u_dmaEngine_io_dmaResp_valid),
    .io_axiMaster_aw_addr  (io_axiMaster_aw_addr),
    .io_axiMaster_aw_len   (io_axiMaster_aw_len),
    .io_axiMaster_aw_ready (io_axiMaster_aw_ready),
    .io_axiMaster_w_last   (io_axiMaster_w_last),
    .io_axiMaster_b_valid  (io_axiMaster_b_valid),
    .io_axiMaster_b_ready  (io_axiMaster_b_ready),
    .io_axiMaster_ar_addr  (io_axiMaster_ar_addr),
    .io_axiMaster_ar_len   (io_axiMaster_ar_len),
    .io_axiMaster_ar_ready (io_axiMaster_ar_ready),
    .io_axiMaster_r_last   (io_axiMaster_r_last),
    .io_axiMaster_r_valid  (io_axiMaster_r_valid),
    .io_axiMaster_r_ready  (io_axiMaster_r_ready)
  );	// C:\\Users\\admin\\.bazel\\2ryzlsy4\\execroot\\_main\\hdl\\chisel\\src\\accel\\npu\\NpuTop.scala:74:27
  AttnEngine u_attnEngine (	// C:\\Users\\admin\\.bazel\\2ryzlsy4\\execroot\\_main\\hdl\\chisel\\src\\accel\\npu\\NpuTop.scala:100:28
    .clock   (clock),
    .reset   (reset),
    .io_done (_u_attnEngine_io_done)
  );	// C:\\Users\\admin\\.bazel\\2ryzlsy4\\execroot\\_main\\hdl\\chisel\\src\\accel\\npu\\NpuTop.scala:100:28
  assign io_cmd_ready = _u_npuCore_io_cmd_ready;	// C:\\Users\\admin\\.bazel\\2ryzlsy4\\execroot\\_main\\hdl\\chisel\\src\\accel\\npu\\NpuTop.scala:47:7, :71:25
  assign io_completion_errCode = 8'h0;	// C:\\Users\\admin\\.bazel\\2ryzlsy4\\execroot\\_main\\hdl\\chisel\\src\\accel\\npu\\NpuTop.scala:47:7, :71:25
  assign io_axiMaster_aw_id = 4'h0;	// C:\\Users\\admin\\.bazel\\2ryzlsy4\\execroot\\_main\\hdl\\chisel\\src\\accel\\npu\\NpuTop.scala:47:7
  assign io_axiMaster_aw_size = 3'h2;	// C:\\Users\\admin\\.bazel\\2ryzlsy4\\execroot\\_main\\hdl\\chisel\\src\\accel\\npu\\NpuTop.scala:47:7, :74:27
  assign io_axiMaster_aw_burst = 2'h1;	// C:\\Users\\admin\\.bazel\\2ryzlsy4\\execroot\\_main\\hdl\\chisel\\src\\accel\\npu\\NpuTop.scala:47:7
  assign io_axiMaster_aw_lock = 1'h0;	// C:\\Users\\admin\\.bazel\\2ryzlsy4\\execroot\\_main\\hdl\\chisel\\src\\accel\\npu\\NpuTop.scala:47:7
  assign io_axiMaster_aw_cache = 4'h0;	// C:\\Users\\admin\\.bazel\\2ryzlsy4\\execroot\\_main\\hdl\\chisel\\src\\accel\\npu\\NpuTop.scala:47:7
  assign io_axiMaster_aw_prot = 3'h0;	// C:\\Users\\admin\\.bazel\\2ryzlsy4\\execroot\\_main\\hdl\\chisel\\src\\accel\\npu\\NpuTop.scala:47:7, :71:25, :74:27
  assign io_axiMaster_aw_qos = 4'h0;	// C:\\Users\\admin\\.bazel\\2ryzlsy4\\execroot\\_main\\hdl\\chisel\\src\\accel\\npu\\NpuTop.scala:47:7
  assign io_axiMaster_aw_region = 4'h0;	// C:\\Users\\admin\\.bazel\\2ryzlsy4\\execroot\\_main\\hdl\\chisel\\src\\accel\\npu\\NpuTop.scala:47:7
  assign io_axiMaster_aw_user = 1'h0;	// C:\\Users\\admin\\.bazel\\2ryzlsy4\\execroot\\_main\\hdl\\chisel\\src\\accel\\npu\\NpuTop.scala:47:7
  assign io_axiMaster_aw_valid = 1'h1;	// C:\\Users\\admin\\.bazel\\2ryzlsy4\\execroot\\_main\\hdl\\chisel\\src\\accel\\npu\\NpuTop.scala:47:7
  assign io_axiMaster_w_data = 32'h0;	// C:\\Users\\admin\\.bazel\\2ryzlsy4\\execroot\\_main\\hdl\\chisel\\src\\accel\\npu\\NpuTop.scala:47:7
  assign io_axiMaster_w_strb = 4'h0;	// C:\\Users\\admin\\.bazel\\2ryzlsy4\\execroot\\_main\\hdl\\chisel\\src\\accel\\npu\\NpuTop.scala:47:7
  assign io_axiMaster_w_user = 1'h0;	// C:\\Users\\admin\\.bazel\\2ryzlsy4\\execroot\\_main\\hdl\\chisel\\src\\accel\\npu\\NpuTop.scala:47:7
  assign io_axiMaster_w_valid = 1'h0;	// C:\\Users\\admin\\.bazel\\2ryzlsy4\\execroot\\_main\\hdl\\chisel\\src\\accel\\npu\\NpuTop.scala:47:7
  assign io_axiMaster_ar_id = 4'h0;	// C:\\Users\\admin\\.bazel\\2ryzlsy4\\execroot\\_main\\hdl\\chisel\\src\\accel\\npu\\NpuTop.scala:47:7
  assign io_axiMaster_ar_size = 3'h2;	// C:\\Users\\admin\\.bazel\\2ryzlsy4\\execroot\\_main\\hdl\\chisel\\src\\accel\\npu\\NpuTop.scala:47:7, :74:27
  assign io_axiMaster_ar_burst = 2'h1;	// C:\\Users\\admin\\.bazel\\2ryzlsy4\\execroot\\_main\\hdl\\chisel\\src\\accel\\npu\\NpuTop.scala:47:7
  assign io_axiMaster_ar_lock = 1'h0;	// C:\\Users\\admin\\.bazel\\2ryzlsy4\\execroot\\_main\\hdl\\chisel\\src\\accel\\npu\\NpuTop.scala:47:7
  assign io_axiMaster_ar_cache = 4'h0;	// C:\\Users\\admin\\.bazel\\2ryzlsy4\\execroot\\_main\\hdl\\chisel\\src\\accel\\npu\\NpuTop.scala:47:7
  assign io_axiMaster_ar_prot = 3'h0;	// C:\\Users\\admin\\.bazel\\2ryzlsy4\\execroot\\_main\\hdl\\chisel\\src\\accel\\npu\\NpuTop.scala:47:7, :71:25, :74:27
  assign io_axiMaster_ar_qos = 4'h0;	// C:\\Users\\admin\\.bazel\\2ryzlsy4\\execroot\\_main\\hdl\\chisel\\src\\accel\\npu\\NpuTop.scala:47:7
  assign io_axiMaster_ar_region = 4'h0;	// C:\\Users\\admin\\.bazel\\2ryzlsy4\\execroot\\_main\\hdl\\chisel\\src\\accel\\npu\\NpuTop.scala:47:7
  assign io_axiMaster_ar_user = 1'h0;	// C:\\Users\\admin\\.bazel\\2ryzlsy4\\execroot\\_main\\hdl\\chisel\\src\\accel\\npu\\NpuTop.scala:47:7
  assign io_axiMaster_ar_valid = 1'h1;	// C:\\Users\\admin\\.bazel\\2ryzlsy4\\execroot\\_main\\hdl\\chisel\\src\\accel\\npu\\NpuTop.scala:47:7
  assign io_perfMatMulCount = r_matmulCount;	// C:\\Users\\admin\\.bazel\\2ryzlsy4\\execroot\\_main\\hdl\\chisel\\src\\accel\\npu\\NpuTop.scala:47:7, :193:30
  assign io_perfConvCount = r_convCount;	// C:\\Users\\admin\\.bazel\\2ryzlsy4\\execroot\\_main\\hdl\\chisel\\src\\accel\\npu\\NpuTop.scala:47:7, :194:30
  assign io_perfAttnCount = r_attnCount;	// C:\\Users\\admin\\.bazel\\2ryzlsy4\\execroot\\_main\\hdl\\chisel\\src\\accel\\npu\\NpuTop.scala:47:7, :195:30
  assign io_perfSparseCount = 32'h0;	// C:\\Users\\admin\\.bazel\\2ryzlsy4\\execroot\\_main\\hdl\\chisel\\src\\accel\\npu\\NpuTop.scala:47:7
endmodule

