// Generated by CIRCT firtool-1.149.0

// Include register initializers in init blocks unless synthesis is set
`ifndef RANDOMIZE
  `ifdef RANDOMIZE_REG_INIT
    `define RANDOMIZE
  `endif // RANDOMIZE_REG_INIT
`endif // not def RANDOMIZE
`ifndef SYNTHESIS
  `ifndef ENABLE_INITIAL_REG_
    `define ENABLE_INITIAL_REG_
  `endif // not def ENABLE_INITIAL_REG_
`endif // not def SYNTHESIS

// Standard header to adapt well known macros for register randomization.

// RANDOM may be set to an expression that produces a 32-bit random unsigned value.
`ifndef RANDOM
  `define RANDOM $random
`endif // not def RANDOM

// Users can define INIT_RANDOM as general code that gets injected into the
// initializer block for modules with registers.
`ifndef INIT_RANDOM
  `define INIT_RANDOM
`endif // not def INIT_RANDOM

// If using random initialization, you can also define RANDOMIZE_DELAY to
// customize the delay used, otherwise 0.002 is used.
`ifndef RANDOMIZE_DELAY
  `define RANDOMIZE_DELAY 0.002
`endif // not def RANDOMIZE_DELAY

// Define INIT_RANDOM_PROLOG_ for use in our modules below.
`ifndef INIT_RANDOM_PROLOG_
  `ifdef RANDOMIZE
    `ifdef VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM
    `else  // VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM #`RANDOMIZE_DELAY begin end
    `endif // VERILATOR
  `else  // RANDOMIZE
    `define INIT_RANDOM_PROLOG_
  `endif // RANDOMIZE
`endif // not def INIT_RANDOM_PROLOG_
module SystolicCell(	// C:\\Users\\admin\\.bazel\\2ryzlsy4\\execroot\\_main\\hdl\\chisel\\src\\accel\\npu\\SystolicCell.scala:59:7
  input         clock,	// C:\\Users\\admin\\.bazel\\2ryzlsy4\\execroot\\_main\\hdl\\chisel\\src\\accel\\npu\\SystolicCell.scala:59:7
                reset,	// C:\\Users\\admin\\.bazel\\2ryzlsy4\\execroot\\_main\\hdl\\chisel\\src\\accel\\npu\\SystolicCell.scala:59:7
  input  [7:0]  io_aIn,	// C:\\Users\\admin\\.bazel\\2ryzlsy4\\execroot\\_main\\hdl\\chisel\\src\\accel\\npu\\SystolicCell.scala:64:14
                io_bIn,	// C:\\Users\\admin\\.bazel\\2ryzlsy4\\execroot\\_main\\hdl\\chisel\\src\\accel\\npu\\SystolicCell.scala:64:14
  input  [15:0] io_cIn,	// C:\\Users\\admin\\.bazel\\2ryzlsy4\\execroot\\_main\\hdl\\chisel\\src\\accel\\npu\\SystolicCell.scala:64:14
  output [7:0]  io_aOut,	// C:\\Users\\admin\\.bazel\\2ryzlsy4\\execroot\\_main\\hdl\\chisel\\src\\accel\\npu\\SystolicCell.scala:64:14
                io_bOut,	// C:\\Users\\admin\\.bazel\\2ryzlsy4\\execroot\\_main\\hdl\\chisel\\src\\accel\\npu\\SystolicCell.scala:64:14
  output [15:0] io_cOut,	// C:\\Users\\admin\\.bazel\\2ryzlsy4\\execroot\\_main\\hdl\\chisel\\src\\accel\\npu\\SystolicCell.scala:64:14
  input         io_en,	// C:\\Users\\admin\\.bazel\\2ryzlsy4\\execroot\\_main\\hdl\\chisel\\src\\accel\\npu\\SystolicCell.scala:64:14
                io_clear	// C:\\Users\\admin\\.bazel\\2ryzlsy4\\execroot\\_main\\hdl\\chisel\\src\\accel\\npu\\SystolicCell.scala:64:14
);

  reg [15:0] productReg;	// C:\\Users\\admin\\.bazel\\2ryzlsy4\\execroot\\_main\\hdl\\chisel\\src\\accel\\npu\\SystolicCell.scala:99:27
  reg [15:0] partialReg;	// C:\\Users\\admin\\.bazel\\2ryzlsy4\\execroot\\_main\\hdl\\chisel\\src\\accel\\npu\\SystolicCell.scala:100:27
  reg        clearReg;	// C:\\Users\\admin\\.bazel\\2ryzlsy4\\execroot\\_main\\hdl\\chisel\\src\\accel\\npu\\SystolicCell.scala:101:27
  reg [7:0]  aReg;	// C:\\Users\\admin\\.bazel\\2ryzlsy4\\execroot\\_main\\hdl\\chisel\\src\\accel\\npu\\SystolicCell.scala:118:23
  reg [7:0]  bReg;	// C:\\Users\\admin\\.bazel\\2ryzlsy4\\execroot\\_main\\hdl\\chisel\\src\\accel\\npu\\SystolicCell.scala:121:23
  reg [15:0] cReg;	// C:\\Users\\admin\\.bazel\\2ryzlsy4\\execroot\\_main\\hdl\\chisel\\src\\accel\\npu\\SystolicCell.scala:124:21
  always @(posedge clock) begin	// C:\\Users\\admin\\.bazel\\2ryzlsy4\\execroot\\_main\\hdl\\chisel\\src\\accel\\npu\\SystolicCell.scala:59:7
    if (reset) begin	// C:\\Users\\admin\\.bazel\\2ryzlsy4\\execroot\\_main\\hdl\\chisel\\src\\accel\\npu\\SystolicCell.scala:59:7
      productReg <= 16'h0;	// C:\\Users\\admin\\.bazel\\2ryzlsy4\\execroot\\_main\\hdl\\chisel\\src\\accel\\npu\\SystolicCell.scala:99:27
      partialReg <= 16'h0;	// C:\\Users\\admin\\.bazel\\2ryzlsy4\\execroot\\_main\\hdl\\chisel\\src\\accel\\npu\\SystolicCell.scala:99:27, :100:27
      clearReg <= 1'h0;	// C:\\Users\\admin\\.bazel\\2ryzlsy4\\execroot\\_main\\hdl\\chisel\\src\\accel\\npu\\SystolicCell.scala:101:27
      aReg <= 8'h0;	// C:\\Users\\admin\\.bazel\\2ryzlsy4\\execroot\\_main\\hdl\\chisel\\src\\accel\\npu\\SystolicCell.scala:118:23
      bReg <= 8'h0;	// C:\\Users\\admin\\.bazel\\2ryzlsy4\\execroot\\_main\\hdl\\chisel\\src\\accel\\npu\\SystolicCell.scala:118:23, :121:23
      cReg <= 16'h0;	// C:\\Users\\admin\\.bazel\\2ryzlsy4\\execroot\\_main\\hdl\\chisel\\src\\accel\\npu\\SystolicCell.scala:99:27, :124:21
    end
    else if (io_en) begin	// C:\\Users\\admin\\.bazel\\2ryzlsy4\\execroot\\_main\\hdl\\chisel\\src\\accel\\npu\\SystolicCell.scala:64:14
      productReg <= {{8{io_aIn[7]}}, io_aIn} * {{8{io_bIn[7]}}, io_bIn};	// C:\\Users\\admin\\.bazel\\2ryzlsy4\\execroot\\_main\\hdl\\chisel\\src\\accel\\npu\\SystolicCell.scala:99:27, :104:26
      partialReg <= io_cIn;	// C:\\Users\\admin\\.bazel\\2ryzlsy4\\execroot\\_main\\hdl\\chisel\\src\\accel\\npu\\SystolicCell.scala:100:27
      clearReg <= io_clear;	// C:\\Users\\admin\\.bazel\\2ryzlsy4\\execroot\\_main\\hdl\\chisel\\src\\accel\\npu\\SystolicCell.scala:101:27
      aReg <= io_aIn;	// C:\\Users\\admin\\.bazel\\2ryzlsy4\\execroot\\_main\\hdl\\chisel\\src\\accel\\npu\\SystolicCell.scala:118:23
      bReg <= io_bIn;	// C:\\Users\\admin\\.bazel\\2ryzlsy4\\execroot\\_main\\hdl\\chisel\\src\\accel\\npu\\SystolicCell.scala:121:23
      cReg <= (clearReg ? 16'h0 : partialReg) + productReg;	// C:\\Users\\admin\\.bazel\\2ryzlsy4\\execroot\\_main\\hdl\\chisel\\src\\accel\\npu\\SystolicCell.scala:99:27, :100:27, :101:27, :110:20, :111:25, :124:21
    end
  end // always @(posedge)
  `ifdef ENABLE_INITIAL_REG_	// C:\\Users\\admin\\.bazel\\2ryzlsy4\\execroot\\_main\\hdl\\chisel\\src\\accel\\npu\\SystolicCell.scala:59:7
    `ifdef FIRRTL_BEFORE_INITIAL	// C:\\Users\\admin\\.bazel\\2ryzlsy4\\execroot\\_main\\hdl\\chisel\\src\\accel\\npu\\SystolicCell.scala:59:7
      `FIRRTL_BEFORE_INITIAL	// C:\\Users\\admin\\.bazel\\2ryzlsy4\\execroot\\_main\\hdl\\chisel\\src\\accel\\npu\\SystolicCell.scala:59:7
    `endif // FIRRTL_BEFORE_INITIAL
    initial begin	// C:\\Users\\admin\\.bazel\\2ryzlsy4\\execroot\\_main\\hdl\\chisel\\src\\accel\\npu\\SystolicCell.scala:59:7
      automatic logic [31:0] _RANDOM[0:2];	// C:\\Users\\admin\\.bazel\\2ryzlsy4\\execroot\\_main\\hdl\\chisel\\src\\accel\\npu\\SystolicCell.scala:59:7
      `ifdef INIT_RANDOM_PROLOG_	// C:\\Users\\admin\\.bazel\\2ryzlsy4\\execroot\\_main\\hdl\\chisel\\src\\accel\\npu\\SystolicCell.scala:59:7
        `INIT_RANDOM_PROLOG_	// C:\\Users\\admin\\.bazel\\2ryzlsy4\\execroot\\_main\\hdl\\chisel\\src\\accel\\npu\\SystolicCell.scala:59:7
      `endif // INIT_RANDOM_PROLOG_
      `ifdef RANDOMIZE_REG_INIT	// C:\\Users\\admin\\.bazel\\2ryzlsy4\\execroot\\_main\\hdl\\chisel\\src\\accel\\npu\\SystolicCell.scala:59:7
        for (logic [1:0] i = 2'h0; i < 2'h3; i += 2'h1) begin
          _RANDOM[i] = `RANDOM;	// C:\\Users\\admin\\.bazel\\2ryzlsy4\\execroot\\_main\\hdl\\chisel\\src\\accel\\npu\\SystolicCell.scala:59:7
        end	// C:\\Users\\admin\\.bazel\\2ryzlsy4\\execroot\\_main\\hdl\\chisel\\src\\accel\\npu\\SystolicCell.scala:59:7
        productReg = _RANDOM[2'h0][15:0];	// C:\\Users\\admin\\.bazel\\2ryzlsy4\\execroot\\_main\\hdl\\chisel\\src\\accel\\npu\\SystolicCell.scala:59:7, :99:27
        partialReg = _RANDOM[2'h0][31:16];	// C:\\Users\\admin\\.bazel\\2ryzlsy4\\execroot\\_main\\hdl\\chisel\\src\\accel\\npu\\SystolicCell.scala:59:7, :99:27, :100:27
        clearReg = _RANDOM[2'h1][0];	// C:\\Users\\admin\\.bazel\\2ryzlsy4\\execroot\\_main\\hdl\\chisel\\src\\accel\\npu\\SystolicCell.scala:59:7, :101:27
        aReg = _RANDOM[2'h1][8:1];	// C:\\Users\\admin\\.bazel\\2ryzlsy4\\execroot\\_main\\hdl\\chisel\\src\\accel\\npu\\SystolicCell.scala:59:7, :101:27, :118:23
        bReg = _RANDOM[2'h1][16:9];	// C:\\Users\\admin\\.bazel\\2ryzlsy4\\execroot\\_main\\hdl\\chisel\\src\\accel\\npu\\SystolicCell.scala:59:7, :101:27, :121:23
        cReg = {_RANDOM[2'h1][31:17], _RANDOM[2'h2][0]};	// C:\\Users\\admin\\.bazel\\2ryzlsy4\\execroot\\_main\\hdl\\chisel\\src\\accel\\npu\\SystolicCell.scala:59:7, :101:27, :124:21
      `endif // RANDOMIZE_REG_INIT
    end // initial
    `ifdef FIRRTL_AFTER_INITIAL	// C:\\Users\\admin\\.bazel\\2ryzlsy4\\execroot\\_main\\hdl\\chisel\\src\\accel\\npu\\SystolicCell.scala:59:7
      `FIRRTL_AFTER_INITIAL	// C:\\Users\\admin\\.bazel\\2ryzlsy4\\execroot\\_main\\hdl\\chisel\\src\\accel\\npu\\SystolicCell.scala:59:7
    `endif // FIRRTL_AFTER_INITIAL
  `endif // ENABLE_INITIAL_REG_
  assign io_aOut = aReg;	// C:\\Users\\admin\\.bazel\\2ryzlsy4\\execroot\\_main\\hdl\\chisel\\src\\accel\\npu\\SystolicCell.scala:59:7, :118:23
  assign io_bOut = bReg;	// C:\\Users\\admin\\.bazel\\2ryzlsy4\\execroot\\_main\\hdl\\chisel\\src\\accel\\npu\\SystolicCell.scala:59:7, :121:23
  assign io_cOut = io_en ? cReg : io_cIn;	// C:\\Users\\admin\\.bazel\\2ryzlsy4\\execroot\\_main\\hdl\\chisel\\src\\accel\\npu\\SystolicCell.scala:59:7, :124:21, :137:17
endmodule

